{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.16.1/kzen-auto-common-0.16.1.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "v35im6qiarc2bi7uzuwidtpecu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.16.1.jar",
          "url": "kzen-auto-common-jvm-0.16.1.jar",
          "size": 475884,
          "sha512": "fc72647ab594ddccc0ddbae7e6db39c2f2e90c38977021a2a16d9cf1cae8ee6b31d8dc00bb33f1979a0014f6b289e91596bd2c8c936cad120dbadc3405ea3de6",
          "sha256": "2dc121ffe59d5f31a07a113498c3cfffcd163c1dc101678be3d40b56dbf9a962",
          "sha1": "4cecea13c8cbc51468880e00bc826078f3e442c9",
          "md5": "bd09de547632aeb5240afe9a08ef46d7"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.16.1.jar",
          "url": "kzen-auto-common-jvm-0.16.1.jar",
          "size": 475884,
          "sha512": "fc72647ab594ddccc0ddbae7e6db39c2f2e90c38977021a2a16d9cf1cae8ee6b31d8dc00bb33f1979a0014f6b289e91596bd2c8c936cad120dbadc3405ea3de6",
          "sha256": "2dc121ffe59d5f31a07a113498c3cfffcd163c1dc101678be3d40b56dbf9a962",
          "sha1": "4cecea13c8cbc51468880e00bc826078f3e442c9",
          "md5": "bd09de547632aeb5240afe9a08ef46d7"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.16.1/kzen-auto-common-metadata-0.16.1.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.16.1"
      }
    }
  ]
}
