{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-js/0.29.1/kzen-lib-js-0.29.1.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.29.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-js-0.29.1.klib",
          "url": "kzen-lib-js-js-0.29.1.klib",
          "size": 7476,
          "sha512": "54baa0b915183695ba8f643b479f2e287d87a77acf4bf6c27d821bd064aced6f658cdc16346a2e17d88260fb91d9e4854e0318ef3ca84bc746600124cea1abff",
          "sha256": "fb9d56fc082e6493d7c5db34ee95adb3c10e8384b089b6e613d05b5b621e44e8",
          "sha1": "37430cc3bd86c13e288da15dfa8eee7f8a060130",
          "md5": "60f16976f2e1d97ea0f4bdc32feadc0b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.29.1"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-js-0.29.1.klib",
          "url": "kzen-lib-js-js-0.29.1.klib",
          "size": 7476,
          "sha512": "54baa0b915183695ba8f643b479f2e287d87a77acf4bf6c27d821bd064aced6f658cdc16346a2e17d88260fb91d9e4854e0318ef3ca84bc746600124cea1abff",
          "sha256": "fb9d56fc082e6493d7c5db34ee95adb3c10e8384b089b6e613d05b5b621e44e8",
          "sha1": "37430cc3bd86c13e288da15dfa8eee7f8a060130",
          "md5": "60f16976f2e1d97ea0f4bdc32feadc0b"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kzen-lib-js-js-0.29.1-sources.jar",
          "url": "kzen-lib-js-js-0.29.1-sources.jar",
          "size": 1480,
          "sha512": "684ace1de3a946c3829eb416f000cb2aa2efdcd5b017fbd3d4d53a4bb83dd84c49524f8190a8d7cd14e1c2421a300c190e3b7513df70087e4adf7a2012ab7cc0",
          "sha256": "c3f9122f8b127bd2968328ad049aa1cd366273aaa176988c258953fe1abaa9c8",
          "sha1": "02b9be6d268fc88d850d58f47d549de4f56f8dd5",
          "md5": "836add05e8bc7018179ffcf53c591b70"
        }
      ]
    }
  ]
}
