{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.18.1/kzen-auto-common-0.18.1.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "klvkzwkon5ab7pnlei5ta55gj4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-metadata-0.18.1.jar",
          "url": "kzen-auto-common-metadata-0.18.1.jar",
          "size": 103316,
          "sha512": "5abcb2ad93fa9003e52f6d61580088ceacfaf1434aa0e2167036a22aaa8ad4ef0b4bff12e086d917711e454fc1868c9927307daf55e0632c8ddbc87807bb267f",
          "sha256": "29adff67a046ece227c8b59f1cc4c74ccd990b53db7c59f86d967cc19c7ab3ec",
          "sha1": "8ebc97565b824ae958966f3282f500db76658046",
          "md5": "f2b692337ba56648d53f9edec61eaf7a"
        }
      ]
    }
  ]
}
