{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6zhiom2d4fa3bjgh7gywfm5oji"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.20.0.jar",
          "url": "kzen-lib-js-0.20.0.jar",
          "size": 45115,
          "sha512": "e83e385fd19f5f80dd5f1de410ec0520326919a35b8b67aafe0a282ee257252969795a62d8db677a0670bac4ecdff9760d5dd571024c3636535c0fe8eff8ea04",
          "sha256": "d0e9bf004566b9729e01e74a8b84e621c84459306d4a64ada35af229c53489c3",
          "sha1": "edb4582a944811091fe82c29a342217d8dfb7940",
          "md5": "44f07d305da4fecdf6241f5953845419"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.20.0.jar",
          "url": "kzen-lib-js-0.20.0.jar",
          "size": 45115,
          "sha512": "e83e385fd19f5f80dd5f1de410ec0520326919a35b8b67aafe0a282ee257252969795a62d8db677a0670bac4ecdff9760d5dd571024c3636535c0fe8eff8ea04",
          "sha256": "d0e9bf004566b9729e01e74a8b84e621c84459306d4a64ada35af229c53489c3",
          "sha1": "edb4582a944811091fe82c29a342217d8dfb7940",
          "md5": "44f07d305da4fecdf6241f5953845419"
        }
      ]
    },
    {
      "name": "jsCommonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
