{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "7r6gld2y75ah5l5nxf555zsv4u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.17.0.jar",
          "url": "kzen-lib-jvm-0.17.0.jar",
          "size": 66280,
          "sha512": "d370d94ff307503718cdf38936da0ac83a139a7518a95b19055b2bfb2435fcd5e43c17b8cef8515266cac019a2cbd149e32efb919940d86a6f7805591c337994",
          "sha256": "2c9995424a54dbb42271070b99de383de1303a58286cd9ca38c80fad4b6cce65",
          "sha1": "e3f2dc97957fe60752f73426d53c167752f2de6b",
          "md5": "aa3a8c9cf5e2a73319d0cd3fcc804a92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.17.0.jar",
          "url": "kzen-lib-jvm-0.17.0.jar",
          "size": 66280,
          "sha512": "d370d94ff307503718cdf38936da0ac83a139a7518a95b19055b2bfb2435fcd5e43c17b8cef8515266cac019a2cbd149e32efb919940d86a6f7805591c337994",
          "sha256": "2c9995424a54dbb42271070b99de383de1303a58286cd9ca38c80fad4b6cce65",
          "sha1": "e3f2dc97957fe60752f73426d53c167752f2de6b",
          "md5": "aa3a8c9cf5e2a73319d0cd3fcc804a92"
        }
      ]
    }
  ]
}
