{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.22.1/kzen-lib-common-0.22.1.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.22.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.22.1.jar",
          "url": "kzen-lib-common-jvm-0.22.1.jar",
          "size": 607370,
          "sha512": "7923a9529eec3bb155fbe08375326d9b892f08438c1aa67c61714319793b1965e7afb98be63b0d03996f425055d2871ce9b699a0ed69a2580dbbef3dd2e221e7",
          "sha256": "184363503c9a5193d5d3506c2d8908baf19e0aa6644f26c6fd21337eeffccfab",
          "sha1": "9b164a7847f8df3f0559821cc0ce289a48a108c0",
          "md5": "64ba1f7f95b68cadbca1960daa1493e4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.22.1.jar",
          "url": "kzen-lib-common-jvm-0.22.1.jar",
          "size": 607370,
          "sha512": "7923a9529eec3bb155fbe08375326d9b892f08438c1aa67c61714319793b1965e7afb98be63b0d03996f425055d2871ce9b699a0ed69a2580dbbef3dd2e221e7",
          "sha256": "184363503c9a5193d5d3506c2d8908baf19e0aa6644f26c6fd21337eeffccfab",
          "sha1": "9b164a7847f8df3f0559821cc0ce289a48a108c0",
          "md5": "64ba1f7f95b68cadbca1960daa1493e4"
        }
      ]
    }
  ]
}
