{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-metadata-0.26.0.jar",
          "url": "kzen-lib-common-0.26.0.jar",
          "size": 56630,
          "sha512": "4e0265d0fe690a310d9bbe84f807ff319891494a6b37239ad8bda51619ae3b849c6fb377786c9000c9ff5d7c4e8d21aea0601bdd03d39139f51d1c6af71c4123",
          "sha256": "4c14fdb77c9b473b51357ef5ffe07b003619ce08379043da9eeb58f735fc6406",
          "sha1": "f7111083bab72e8ba8590edd61770dcd8bc4d1cc",
          "md5": "30a9f51ee5f66f8afe49035b703c4bd8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kzen-lib-common-kotlin-0.26.0-sources.jar",
          "url": "kzen-lib-common-0.26.0-sources.jar",
          "size": 110132,
          "sha512": "f18e2a1cc5848c74e5217bd1e3314ec41dd58eb54c4649465472e2f1dc9f7cb04c6b63fa14d3d8cb77384be23b8fed084bcbf65f827407da55931e468fd31536",
          "sha256": "24382fd25de0a669cb5851d0dca3d098445528f3c3a17d56e5b32e558fbda702",
          "sha1": "07909d9d661033c31015fb85e075a43c49124be5",
          "md5": "b50ce16d0d9064bb2916579d8ea75afc"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-lib-common-js/0.26.0/kzen-lib-common-js-0.26.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-js",
        "version": "0.26.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-lib-common-js/0.26.0/kzen-lib-common-js-0.26.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-js",
        "version": "0.26.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-lib-common-js/0.26.0/kzen-lib-common-js-0.26.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-js",
        "version": "0.26.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-lib-common-jvm/0.26.0/kzen-lib-common-jvm-0.26.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-jvm",
        "version": "0.26.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-lib-common-jvm/0.26.0/kzen-lib-common-jvm-0.26.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-jvm",
        "version": "0.26.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-lib-common-jvm/0.26.0/kzen-lib-common-jvm-0.26.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-jvm",
        "version": "0.26.0"
      }
    }
  ]
}
