{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.23.0/kzen-auto-common-0.23.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.23.0.jar",
          "url": "kzen-auto-common-jvm-0.23.0.jar",
          "size": 654343,
          "sha512": "7d0fc320b3b14f15059eec79d75a810b13eb51adcd2d43658076b58d86516778251c3266841a596018785f9f2e250c91ae990982107e3288f4fac56080a53445",
          "sha256": "5896281571ff5f702e6158583447218bf105897c13490075eaf6f8b606000620",
          "sha1": "3a8b568273fe8d2e349251ddb4e5e441953b332e",
          "md5": "8e2676d88f652ec7a831d3b585211982"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.213-kotlin-1.5.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.213-kotlin-1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.23.0.jar",
          "url": "kzen-auto-common-jvm-0.23.0.jar",
          "size": 654343,
          "sha512": "7d0fc320b3b14f15059eec79d75a810b13eb51adcd2d43658076b58d86516778251c3266841a596018785f9f2e250c91ae990982107e3288f4fac56080a53445",
          "sha256": "5896281571ff5f702e6158583447218bf105897c13490075eaf6f8b606000620",
          "sha1": "3a8b568273fe8d2e349251ddb4e5e441953b332e",
          "md5": "8e2676d88f652ec7a831d3b585211982"
        }
      ]
    }
  ]
}
