{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.18.1/kzen-auto-common-0.18.1.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "klvkzwkon5ab7pnlei5ta55gj4"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.18.1.jar",
          "url": "kzen-auto-common-jvm-0.18.1.jar",
          "size": 515022,
          "sha512": "133b7c7af3c434f01ab57cc6757425ed0d7f27fa13d504f1aeb3a92338502dc88fa985f25907259279954be452ebebe97cb7216e16d2ff3656a15aee27064a03",
          "sha256": "61e05f99f7dbceb83bc49eb08b6dcf43f9a99c1e1854292c5230c35300cb78c8",
          "sha1": "91c567cf24a30381f14c0b0e352360b24c361b80",
          "md5": "4b6db4e233a6d2714d3b0c89bb7b647f"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.18.1.jar",
          "url": "kzen-auto-common-jvm-0.18.1.jar",
          "size": 515022,
          "sha512": "133b7c7af3c434f01ab57cc6757425ed0d7f27fa13d504f1aeb3a92338502dc88fa985f25907259279954be452ebebe97cb7216e16d2ff3656a15aee27064a03",
          "sha256": "61e05f99f7dbceb83bc49eb08b6dcf43f9a99c1e1854292c5230c35300cb78c8",
          "sha1": "91c567cf24a30381f14c0b0e352360b24c361b80",
          "md5": "4b6db4e233a6d2714d3b0c89bb7b647f"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.18.1/kzen-auto-common-metadata-0.18.1.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.18.1"
      }
    }
  ]
}
