{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "klvkzwkon5ab7pnlei5ta55gj4"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.18.1.jar",
          "url": "kzen-auto-js-0.18.1.jar",
          "size": 381188,
          "sha512": "0aa125944920b1346133066a3a198ee77fe0a9c5fd2c69ad00eeb1a673cb9490da21d611076e725faed99eabec3f3cc9c8c8db4e1bd318beef3cf708e88f3457",
          "sha256": "469a0777fdfdca73f4bd047a4a6f4883cc48d964bc74b10f33a13b6fdbf746f4",
          "sha1": "1d3581fa903a51ead4391644a58ff15ab3496774",
          "md5": "17dc6f3b1ec582c7479a319a52c8593f"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-assembly",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react",
          "version": {
            "requires": "16.13.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "16.13.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-styled",
          "version": {
            "requires": "5.2.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.18.1.jar",
          "url": "kzen-auto-js-0.18.1.jar",
          "size": 381188,
          "sha512": "0aa125944920b1346133066a3a198ee77fe0a9c5fd2c69ad00eeb1a673cb9490da21d611076e725faed99eabec3f3cc9c8c8db4e1bd318beef3cf708e88f3457",
          "sha256": "469a0777fdfdca73f4bd047a4a6f4883cc48d964bc74b10f33a13b6fdbf746f4",
          "sha1": "1d3581fa903a51ead4391644a58ff15ab3496774",
          "md5": "17dc6f3b1ec582c7479a319a52c8593f"
        }
      ]
    },
    {
      "name": "js-jsCommonFakeApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
