{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.18.0/kzen-auto-common-0.18.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tlvpymcfkzbztmdd57r4yaqt44"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-metadata-0.18.0.jar",
          "url": "kzen-auto-common-metadata-0.18.0.jar",
          "size": 103300,
          "sha512": "075faf82e80bc42d81aefd0ad3f8277b71c3bcbc00c41db187827fcc1411a3ac9e44e683b4f3ff7bc21d5e39f3600136f692a311a129fde3ce53ff60a21d6660",
          "sha256": "46253af83b89bede585fb2e91eb177de35bde8be5e7cd27256aa7b7362462080",
          "sha1": "35105af93139d6c8beba3d70d0166271afd537d8",
          "md5": "31a948fa5284a119d8888a241f7c004e"
        }
      ]
    }
  ]
}
