{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.18.0/kzen-auto-common-0.18.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "leyf5vl4inefveeqp6jncc6z3i"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-metadata-0.18.0.jar",
          "url": "kzen-auto-common-metadata-0.18.0.jar",
          "size": 103300,
          "sha512": "21385316bf3ba4bbc6b3dccc0565ab8586320a219ec401357350ec98be943e3877c0a4cf9d96ce343321ba0c6411dd16dc74e5937c9719c973efa03301d4fda8",
          "sha256": "68f1ddd4889f30bf99612cb5c0b21f3555fc5a236def7355728370520e644094",
          "sha1": "5830653d75eaa52a9e00351f75f2a94575702495",
          "md5": "2ffc5c5ac6a6d05a853031a3d8d3d4a8"
        }
      ]
    }
  ]
}
