{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.18.0/kzen-lib-common-0.18.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "pkp2lucc5fbnxpas6hvmc6f264"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-metadata-0.18.0.jar",
          "url": "kzen-lib-common-metadata-0.18.0.jar",
          "size": 123112,
          "sha512": "1de33f1c3a1ebda5936cb5bca1d57ea2a1305bf390163ca271db4f11960bb194a3b2c50b38f544e8ea0cb3ce12607dfa43b534a3eac97dc4690a6887f2f93863",
          "sha256": "32c0b8791535b555659b9d0086b421560fb0176bc4c360b9d1867f493484def1",
          "sha1": "50cc58d4adc796a19ccf3bb60d7d9616b6a99791",
          "md5": "c19ca86ffafb66607ed91ba77e152aeb"
        }
      ]
    }
  ]
}
