{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-js/0.28.0/kzen-lib-js-0.28.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-js-0.28.0.klib",
          "url": "kzen-lib-js-js-0.28.0.klib",
          "size": 5644,
          "sha512": "5afcd3ac7f22a39ce2ed4006dd51f65c79ad8c80c0909802176137fbe52f8384d3a1ab05d8a4c199fe98a52fc20c3b941e3a89366b8b1acdecf1013546fa7555",
          "sha256": "42ee1b51eabbfcd7597ec31d0a7addd2fd6d27c849c2b40e3885a70d856035a4",
          "sha1": "df3be594d4137c74d86850e29302e656e02f2ef2",
          "md5": "c6c19f082c88598c13d203aa6ac5b6f2"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.28.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-js-0.28.0.klib",
          "url": "kzen-lib-js-js-0.28.0.klib",
          "size": 5644,
          "sha512": "5afcd3ac7f22a39ce2ed4006dd51f65c79ad8c80c0909802176137fbe52f8384d3a1ab05d8a4c199fe98a52fc20c3b941e3a89366b8b1acdecf1013546fa7555",
          "sha256": "42ee1b51eabbfcd7597ec31d0a7addd2fd6d27c849c2b40e3885a70d856035a4",
          "sha1": "df3be594d4137c74d86850e29302e656e02f2ef2",
          "md5": "c6c19f082c88598c13d203aa6ac5b6f2"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kzen-lib-js-js-0.28.0-sources.jar",
          "url": "kzen-lib-js-js-0.28.0-sources.jar",
          "size": 1480,
          "sha512": "684ace1de3a946c3829eb416f000cb2aa2efdcd5b017fbd3d4d53a4bb83dd84c49524f8190a8d7cd14e1c2421a300c190e3b7513df70087e4adf7a2012ab7cc0",
          "sha256": "c3f9122f8b127bd2968328ad049aa1cd366273aaa176988c258953fe1abaa9c8",
          "sha1": "02b9be6d268fc88d850d58f47d549de4f56f8dd5",
          "md5": "836add05e8bc7018179ffcf53c591b70"
        }
      ]
    }
  ]
}
