{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.28.0/kzen-auto-common-0.28.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.28.0.jar",
          "url": "kzen-auto-common-jvm-0.28.0.jar",
          "size": 610821,
          "sha512": "82cf0c7c815c1c9fcdace97a10fdc4b335d4f44012ded3c48572cc2252cdc48954f26c8ddfa7c85baea51fd20548bd443837f789c0830ce5101fbe317f3c46a8",
          "sha256": "01ec564616db5aa68e52d9eb7514881c3dec71e8678691ca0b0ba23f37ad505e",
          "sha1": "bcaa7ae08a3651d8986bdd2718a6bb08b49f48e0",
          "md5": "b4039e14d0c47ce406ccd5778ee81b53"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.28.0.jar",
          "url": "kzen-auto-common-jvm-0.28.0.jar",
          "size": 610821,
          "sha512": "82cf0c7c815c1c9fcdace97a10fdc4b335d4f44012ded3c48572cc2252cdc48954f26c8ddfa7c85baea51fd20548bd443837f789c0830ce5101fbe317f3c46a8",
          "sha256": "01ec564616db5aa68e52d9eb7514881c3dec71e8678691ca0b0ba23f37ad505e",
          "sha1": "bcaa7ae08a3651d8986bdd2718a6bb08b49f48e0",
          "md5": "b4039e14d0c47ce406ccd5778ee81b53"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.28.0-sources.jar",
          "url": "kzen-auto-common-jvm-0.28.0-sources.jar",
          "size": 123984,
          "sha512": "949c3f75311aef4ac6de4a8b586564dcecf6cf75ec1bedec9999514fbca9e124c9c07895ad3b23ed21ff9c42df68f46a2c8ca308815d0ceea8cca4e2b48b391a",
          "sha256": "b6e37498d6e7b5e3d3aa69905e87c1df65787fe15a64677da56625f1fe1b0350",
          "sha1": "e6e9c5f74c3999c1ae5dbe5b9b8f841b576b8626",
          "md5": "1b713fe88c80e622dcfb75a117725799"
        }
      ]
    }
  ]
}
