{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.26.0.klib",
          "url": "kzen-lib-js-0.26.0.klib",
          "size": 5330,
          "sha512": "1bf4557d479c000e74167cccfca4e0fbded5a7ec939aff904a32e2eb4fa6d97763140e3637ade03d7d686d683b896036d1f110b272564cd61401256e88dd0b8e",
          "sha256": "ffc598e339a073f536a9dd67e19382301b969f12a0da59dbc54dd703c970e0b2",
          "sha1": "92e65c467486e326898ae15acba054460e27ce25",
          "md5": "acaf1e82d4e2166dc50d1a784fd9b372"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.26.0.klib",
          "url": "kzen-lib-js-0.26.0.klib",
          "size": 5330,
          "sha512": "1bf4557d479c000e74167cccfca4e0fbded5a7ec939aff904a32e2eb4fa6d97763140e3637ade03d7d686d683b896036d1f110b272564cd61401256e88dd0b8e",
          "sha256": "ffc598e339a073f536a9dd67e19382301b969f12a0da59dbc54dd703c970e0b2",
          "sha1": "92e65c467486e326898ae15acba054460e27ce25",
          "md5": "acaf1e82d4e2166dc50d1a784fd9b372"
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kzen-lib-js-0.26.0-sources.jar",
          "url": "kzen-lib-js-0.26.0-sources.jar",
          "size": 1461,
          "sha512": "22d8062143f459b59e3a1ac6c101968219517773b4d7afcb8cf24927064c64946c86978245b24804051469a6392f5b5a9a05aaa5ff7f924308fdbb58d6fa824d",
          "sha256": "4654af371a82ccea9749fdf65540437c0299a54717ba927dc5b7847ea9ba8525",
          "sha1": "eaca0b9984e4903d3c136767f62691ee454d55e5",
          "md5": "8d06bbca5c0b2bf1253f639458b9962d"
        }
      ]
    }
  ]
}
