{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6zhiom2d4fa3bjgh7gywfm5oji"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.20.0.jar",
          "url": "kzen-lib-jvm-0.20.0.jar",
          "size": 67513,
          "sha512": "56803d7acc92c052757cae82429fc5f54a84e0c2dbfb4bd1f8a210cd9680ae6ac0135e0b4d3ffcb6f6ae1bea56ebdd0d9a7c14de3c44eb93b14abb15d1951b6e",
          "sha256": "e57ce97b9cae7f56ac892afd25ed404319227e991d077212b7fa3d763463ec9a",
          "sha1": "b63fe14a70612a04bd8eef2cff66341aab1a8348",
          "md5": "105433c8dbb20be880721c3ad6e2c89c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.20.0.jar",
          "url": "kzen-lib-jvm-0.20.0.jar",
          "size": 67513,
          "sha512": "56803d7acc92c052757cae82429fc5f54a84e0c2dbfb4bd1f8a210cd9680ae6ac0135e0b4d3ffcb6f6ae1bea56ebdd0d9a7c14de3c44eb93b14abb15d1951b6e",
          "sha256": "e57ce97b9cae7f56ac892afd25ed404319227e991d077212b7fa3d763463ec9a",
          "sha1": "b63fe14a70612a04bd8eef2cff66341aab1a8348",
          "md5": "105433c8dbb20be880721c3ad6e2c89c"
        }
      ]
    }
  ]
}
