{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-metadata-0.28.0.jar",
          "url": "kzen-auto-common-0.28.0.jar",
          "size": 79335,
          "sha512": "857391121fbc834d36fccefa614aeeddc5f5f5de33390a6bbec01f1e7d847833317ffe947ab25029bc75297aa3e835bd9d963321938da8209c54aae113be3d4c",
          "sha256": "ab973338b5853b8f9f1b38a0a80b994de32627fcb310390bcb75b116893a26e8",
          "sha1": "3df023f7e2dc3c3a310e661b9e46e17a0cc7be49",
          "md5": "9bd11f8b1bf31dd0c8ce5b4e1bfa9651"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kzen-auto-common-kotlin-0.28.0-sources.jar",
          "url": "kzen-auto-common-0.28.0-sources.jar",
          "size": 121029,
          "sha512": "50eecc6b0a3767a91b1734c725301c1eb2f975e706a77e95444cb07c2144fe9f901d883c78fe8f29ff2e2d2943529d2fc8853fc314d4883f9d0f4c2560415c4e",
          "sha256": "26ffa86314033a3cda3db83f7e9b384bc0a97e5787e9da96696a18c3e3399ca7",
          "sha1": "6364154a1ce08b05997fb5a5858139cee74dcfee",
          "md5": "b9921171b5b3e1099709ff468b8e8b95"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-common-js/0.28.0/kzen-auto-common-js-0.28.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-js",
        "version": "0.28.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-common-js/0.28.0/kzen-auto-common-js-0.28.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-js",
        "version": "0.28.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-common-js/0.28.0/kzen-auto-common-js-0.28.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-js",
        "version": "0.28.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-auto-common-jvm/0.28.0/kzen-auto-common-jvm-0.28.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-jvm",
        "version": "0.28.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-auto-common-jvm/0.28.0/kzen-auto-common-jvm-0.28.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-jvm",
        "version": "0.28.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-auto-common-jvm/0.28.0/kzen-auto-common-jvm-0.28.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-jvm",
        "version": "0.28.0"
      }
    }
  ]
}
