{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.16.1/kzen-auto-common-0.16.1.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "v35im6qiarc2bi7uzuwidtpecu"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.16.1.jar",
          "url": "kzen-auto-common-js-0.16.1.jar",
          "size": 200665,
          "sha512": "d9647f21e227ce886fd8d749c219e7cddda1ca9733a32775227a90e3e48fc593195c5957a5cd9924db36593e992e5d1ed08b4511d8b722ed1930fcc1d3a37e4e",
          "sha256": "c623692db797e5fb415f005bba31e0b989c7912929a17900e24e5560304d6121",
          "sha1": "d0734466a87a216499f5650e0c6e93ed651cc8ce",
          "md5": "cfac874f369b2797be95ad62d0e0dfca"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.16.1.jar",
          "url": "kzen-auto-common-js-0.16.1.jar",
          "size": 200665,
          "sha512": "d9647f21e227ce886fd8d749c219e7cddda1ca9733a32775227a90e3e48fc593195c5957a5cd9924db36593e992e5d1ed08b4511d8b722ed1930fcc1d3a37e4e",
          "sha256": "c623692db797e5fb415f005bba31e0b989c7912929a17900e24e5560304d6121",
          "sha1": "d0734466a87a216499f5650e0c6e93ed651cc8ce",
          "md5": "cfac874f369b2797be95ad62d0e0dfca"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.16.1/kzen-auto-common-metadata-0.16.1.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.16.1"
      }
    }
  ]
}
