{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qy2plcrkgrg75pocbnl4xgwwbq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.19.0.jar",
          "url": "kzen-lib-jvm-0.19.0.jar",
          "size": 67513,
          "sha512": "b6e637c706ca2b6d5531ffb64a5937d6ebff567ba5613114c42b2565d68ebf187ecd46b8e5b1120bbc360ff0147031bbadbab9f6f62cdcf3167dd9749f2a53af",
          "sha256": "210bebe3ab7686d5b65bd6baffb6a8c4563fdd554bf04b33d5a54fea77aec879",
          "sha1": "08995932f09ef2db8820917465bd301a57a694c5",
          "md5": "2caca908070f2ab7053bcdc881ffc04e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.19.0.jar",
          "url": "kzen-lib-jvm-0.19.0.jar",
          "size": 67513,
          "sha512": "b6e637c706ca2b6d5531ffb64a5937d6ebff567ba5613114c42b2565d68ebf187ecd46b8e5b1120bbc360ff0147031bbadbab9f6f62cdcf3167dd9749f2a53af",
          "sha256": "210bebe3ab7686d5b65bd6baffb6a8c4563fdd554bf04b33d5a54fea77aec879",
          "sha1": "08995932f09ef2db8820917465bd301a57a694c5",
          "md5": "2caca908070f2ab7053bcdc881ffc04e"
        }
      ]
    }
  ]
}
