{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.29.1/kzen-lib-common-0.29.1.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.29.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.29.1.jar",
          "url": "kzen-lib-common-jvm-0.29.1.jar",
          "size": 912296,
          "sha512": "294e3d88d5ff4f0c7a5bf2746e7f6ba78010d8b199226bbd6a91df68e5e5847109a1e5ad7ad464466d11d8146d6de354b4c76df4c6f04e006fadba6081a4cd79",
          "sha256": "d40ba0f4c03e6cab4fc71c1b20d6991dd07a8ac7bafed229bc5a0d4d9851a34e",
          "sha1": "3a328d2df98ed94c314449a242fa09cde8eff662",
          "md5": "56c14dcf36da9b48c2bdfffdc3b8d217"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.29.1.jar",
          "url": "kzen-lib-common-jvm-0.29.1.jar",
          "size": 912296,
          "sha512": "294e3d88d5ff4f0c7a5bf2746e7f6ba78010d8b199226bbd6a91df68e5e5847109a1e5ad7ad464466d11d8146d6de354b4c76df4c6f04e006fadba6081a4cd79",
          "sha256": "d40ba0f4c03e6cab4fc71c1b20d6991dd07a8ac7bafed229bc5a0d4d9851a34e",
          "sha1": "3a328d2df98ed94c314449a242fa09cde8eff662",
          "md5": "56c14dcf36da9b48c2bdfffdc3b8d217"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.29.1-sources.jar",
          "url": "kzen-lib-common-jvm-0.29.1-sources.jar",
          "size": 179123,
          "sha512": "47a1681f9e31f7a21473003c93b290fe0e51b5831fe326af56113c66057dd9754aef2e7cbcbe3ba67fac7263439c859632d8c4347935baeb1bc8fb68d5df7c54",
          "sha256": "52379d313fbf39f7cc48f39d69c5a2a8f0b478754e0617f4529d4f0a3904913a",
          "sha1": "7f981d1f27971f8ad120103e7192eee7810da7f9",
          "md5": "95de769443cbb936dae77548a46c6ea5"
        }
      ]
    }
  ]
}
