{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.28.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-metadata-0.28.1.jar",
          "url": "kzen-auto-js-0.28.1.jar",
          "size": 669,
          "sha512": "770d72cd022b189b4a259384b2483010cee070452fbb51fb30253dfcdef4d3f9d15c7972c8ec782fd2f09fd43f1bc2dd2939059479eb4bf9f56f57684c1e34ab",
          "sha256": "6230e0b2c42b6b091811ce9caba4e22aa67a474fec84d20c66713dcaa1552b00",
          "sha1": "b3b8bf147a210c2f0912cf8f759f1daa4e93153b",
          "md5": "32a7bcaea8de96c10711ccb3ad62f54c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kzen-auto-js-kotlin-0.28.1-sources.jar",
          "url": "kzen-auto-js-0.28.1-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-js-js/0.28.1/kzen-auto-js-js-0.28.1.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-js-js",
        "version": "0.28.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-js-js/0.28.1/kzen-auto-js-js-0.28.1.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-js-js",
        "version": "0.28.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-js-js/0.28.1/kzen-auto-js-js-0.28.1.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-js-js",
        "version": "0.28.1"
      }
    }
  ]
}
