{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.18.0/kzen-lib-common-0.18.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "pkp2lucc5fbnxpas6hvmc6f264"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.18.0.jar",
          "url": "kzen-lib-common-js-0.18.0.jar",
          "size": 279890,
          "sha512": "f599c4ea047918f94b7cf57d07b70ac5d5b3a2c0ce99ec277a176f1776f09a1d721f79771a143e82990145edf6dae37a51d9736eafce8dc3d36e01eaee7e81fe",
          "sha256": "c3303dbfad0e0f98a91fcb8020daa0d8497be2aa198df0dc6845da509bdc5102",
          "sha1": "6e6174f7d9be74a46cc88b8cfa3dfdf2f76ffc65",
          "md5": "a62739ec7ef7c1071af5bac976cd85aa"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.18.0.jar",
          "url": "kzen-lib-common-js-0.18.0.jar",
          "size": 279890,
          "sha512": "f599c4ea047918f94b7cf57d07b70ac5d5b3a2c0ce99ec277a176f1776f09a1d721f79771a143e82990145edf6dae37a51d9736eafce8dc3d36e01eaee7e81fe",
          "sha256": "c3303dbfad0e0f98a91fcb8020daa0d8497be2aa198df0dc6845da509bdc5102",
          "sha1": "6e6174f7d9be74a46cc88b8cfa3dfdf2f76ffc65",
          "md5": "a62739ec7ef7c1071af5bac976cd85aa"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-lib-common-metadata/0.18.0/kzen-lib-common-metadata-0.18.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-metadata",
        "version": "0.18.0"
      }
    }
  ]
}
