{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "577r7knbyrelpmokwykjiznxpi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.16.0.jar",
          "url": "kzen-lib-jvm-0.16.0.jar",
          "size": 66280,
          "sha512": "38379a98adf8858276f95d7ae14c92794b53c070af7eddd914086e234656ac2e6a84f339eacc91efa5ad06f677c871c59f2a716597b2a9b0b6ed9cc0124f5a05",
          "sha256": "d52cb7c2d1197f3021a450ea291656c0622475d2a1290de844af51dd801b69bd",
          "sha1": "735ea300691bc3fd38156a3b0e7c16e43acca957",
          "md5": "39e51062de0b5e45ef1abe22f9bc772f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.16.0.jar",
          "url": "kzen-lib-jvm-0.16.0.jar",
          "size": 66280,
          "sha512": "38379a98adf8858276f95d7ae14c92794b53c070af7eddd914086e234656ac2e6a84f339eacc91efa5ad06f677c871c59f2a716597b2a9b0b6ed9cc0124f5a05",
          "sha256": "d52cb7c2d1197f3021a450ea291656c0622475d2a1290de844af51dd801b69bd",
          "sha1": "735ea300691bc3fd38156a3b0e7c16e43acca957",
          "md5": "39e51062de0b5e45ef1abe22f9bc772f"
        }
      ]
    }
  ]
}
