{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "4htazsilf5gmvks7fvrjsvl6s4"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.16.0.jar",
          "url": "kzen-auto-js-0.16.0.jar",
          "size": 359634,
          "sha512": "ad7fbb10b3927f4d34823be74afcb6f28c5d9c927f65f1ff298c4b17e8efc01b8f30df7545843d0cd0b6b146e53d0c6b4930247f6c62ce03caa310fd795a67ab",
          "sha256": "c788ebd246f387d8892575400a5ef6b856e5b036e0b686ef15d917174551c370",
          "sha1": "21a90120d94f6786a9e9326fe072ee723ec95a7b",
          "md5": "b0a0a2aa3884a8bd5c5cee4ffb812b6d"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-assembly",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react",
          "version": {
            "requires": "16.13.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "16.13.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-styled",
          "version": {
            "requires": "5.2.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.16.0.jar",
          "url": "kzen-auto-js-0.16.0.jar",
          "size": 359634,
          "sha512": "ad7fbb10b3927f4d34823be74afcb6f28c5d9c927f65f1ff298c4b17e8efc01b8f30df7545843d0cd0b6b146e53d0c6b4930247f6c62ce03caa310fd795a67ab",
          "sha256": "c788ebd246f387d8892575400a5ef6b856e5b036e0b686ef15d917174551c370",
          "sha1": "21a90120d94f6786a9e9326fe072ee723ec95a7b",
          "md5": "b0a0a2aa3884a8bd5c5cee4ffb812b6d"
        }
      ]
    },
    {
      "name": "js-jsCommonFakeApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
