{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.17.0/kzen-lib-common-0.17.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "7r6gld2y75ah5l5nxf555zsv4u"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.17.0.jar",
          "url": "kzen-lib-common-jvm-0.17.0.jar",
          "size": 568653,
          "sha512": "20af8d51632ecd63fa6de102a9d52b6d28223a237f9922e68ee43fe7f50f19e630fadfa8a8a56f85db362e4dd84b000a2209e68f9a6891562930f1cf0233d27d",
          "sha256": "e9b90771591b140336e33584d1b60c89a7d04e1a37ffd27ff15c3e77378a70f0",
          "sha1": "99f517937313f2189578c786246490d2f652c92e",
          "md5": "5eeedee01af87472102a3b1df8aff20c"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.17.0.jar",
          "url": "kzen-lib-common-jvm-0.17.0.jar",
          "size": 568653,
          "sha512": "20af8d51632ecd63fa6de102a9d52b6d28223a237f9922e68ee43fe7f50f19e630fadfa8a8a56f85db362e4dd84b000a2209e68f9a6891562930f1cf0233d27d",
          "sha256": "e9b90771591b140336e33584d1b60c89a7d04e1a37ffd27ff15c3e77378a70f0",
          "sha1": "99f517937313f2189578c786246490d2f652c92e",
          "md5": "5eeedee01af87472102a3b1df8aff20c"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-lib-common-metadata/0.17.0/kzen-lib-common-metadata-0.17.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-metadata",
        "version": "0.17.0"
      }
    }
  ]
}
