{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.24.1.jar",
          "url": "kzen-auto-js-0.24.1.jar",
          "size": 509331,
          "sha512": "81de759c0fb8910b122ccf8f3e22a30efa916eb6d1579219d3f0b9eaf1e8d570e1965c165d871f5869cb627fd6456b67c2c241c8e4bd3b345a209eedc919a3e8",
          "sha256": "3340e15ccf72cbba65c6a5b3bf80feea115404632d09eccd4e72f90ffcf08237",
          "sha1": "1afb9334be70145485c56555ab7b1233ac0ef04a",
          "md5": "6c82448b776b4bffa7fcc7214d870c66"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-assembly",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "17.0.2-pre.268-kotlin-1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "17.0.2-pre.268-kotlin-1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-styled",
          "version": {
            "requires": "5.3.3-pre.268-kotlin-1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.268-kotlin-1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.268-kotlin-1.6.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.24.1.jar",
          "url": "kzen-auto-js-0.24.1.jar",
          "size": 509331,
          "sha512": "81de759c0fb8910b122ccf8f3e22a30efa916eb6d1579219d3f0b9eaf1e8d570e1965c165d871f5869cb627fd6456b67c2c241c8e4bd3b345a209eedc919a3e8",
          "sha256": "3340e15ccf72cbba65c6a5b3bf80feea115404632d09eccd4e72f90ffcf08237",
          "sha1": "1afb9334be70145485c56555ab7b1233ac0ef04a",
          "md5": "6c82448b776b4bffa7fcc7214d870c66"
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
