{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "olrzopx3uraoxoa4kczf5f6sr4"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.19.0.jar",
          "url": "kzen-auto-js-0.19.0.jar",
          "size": 381419,
          "sha512": "6a366bd27b78d18967861744a9b4215e10c1be422dd3e99603cfb9c43a5e4ec5276ef8f5edb857a29103280f6661ddb3f42a550bc7609d9730735725339edf19",
          "sha256": "04ff683e6ea77513dea7905aaae68c996aa21e3e1c606f4c703402b856d9d011",
          "sha1": "88f8b74e3617d215798f2d020fc2514c9121e539",
          "md5": "18ca71505d9bcd75354f9112136f9171"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-assembly",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react",
          "version": {
            "requires": "17.0.0-pre.129-kotlin-1.4.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "17.0.0-pre.129-kotlin-1.4.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-styled",
          "version": {
            "requires": "5.2.0-pre.129-kotlin-1.4.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.129-kotlin-1.4.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.129-kotlin-1.4.20"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.19.0.jar",
          "url": "kzen-auto-js-0.19.0.jar",
          "size": 381419,
          "sha512": "6a366bd27b78d18967861744a9b4215e10c1be422dd3e99603cfb9c43a5e4ec5276ef8f5edb857a29103280f6661ddb3f42a550bc7609d9730735725339edf19",
          "sha256": "04ff683e6ea77513dea7905aaae68c996aa21e3e1c606f4c703402b856d9d011",
          "sha1": "88f8b74e3617d215798f2d020fc2514c9121e539",
          "md5": "18ca71505d9bcd75354f9112136f9171"
        }
      ]
    },
    {
      "name": "jsCommonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
