{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.21.0/kzen-lib-common-0.21.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "2iku5ntjuvbwtmfbdcudiiqn2y"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.21.0.jar",
          "url": "kzen-lib-common-jvm-0.21.0.jar",
          "size": 588423,
          "sha512": "1e61b447a49803f6b188cd9f2b3364705c0721132194d78125fb5971577229acd8472d8e282948fe95ec86a937337bef99194914932673e37df8a7d9b2d131f1",
          "sha256": "461e94b07969bd18a7ea613b69dc5e1840ec01692c643caa2a55c61765ed1f4e",
          "sha1": "de5c19d910cd7907ec116d7c03be26001bcfd477",
          "md5": "a4f627baa8f1e7e92296d9bbf6fe6e1d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.21.0.jar",
          "url": "kzen-lib-common-jvm-0.21.0.jar",
          "size": 588423,
          "sha512": "1e61b447a49803f6b188cd9f2b3364705c0721132194d78125fb5971577229acd8472d8e282948fe95ec86a937337bef99194914932673e37df8a7d9b2d131f1",
          "sha256": "461e94b07969bd18a7ea613b69dc5e1840ec01692c643caa2a55c61765ed1f4e",
          "sha1": "de5c19d910cd7907ec116d7c03be26001bcfd477",
          "md5": "a4f627baa8f1e7e92296d9bbf6fe6e1d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-lib-common-metadata/0.21.0/kzen-lib-common-metadata-0.21.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-metadata",
        "version": "0.21.0"
      }
    }
  ]
}
