{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.17.0/kzen-lib-common-0.17.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "7r6gld2y75ah5l5nxf555zsv4u"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.17.0.jar",
          "url": "kzen-lib-common-js-0.17.0.jar",
          "size": 276568,
          "sha512": "80352b0dc68c5b2e379809a0cd49251b89d90353f64bc3e4d7e694c62418072bc949a3eb09e70c534a70ea3f705620ce4bff75e4fd52f1e17ea7eb1ecf7095e2",
          "sha256": "2be1bc06700d34cdcc4ddcc6bfd6a8d1853db16b86b28db6c1db4feb39a25124",
          "sha1": "93417c6946f22464403976504a23735aa715d818",
          "md5": "3861136a7df5baf7439577f399319fb1"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.17.0.jar",
          "url": "kzen-lib-common-js-0.17.0.jar",
          "size": 276568,
          "sha512": "80352b0dc68c5b2e379809a0cd49251b89d90353f64bc3e4d7e694c62418072bc949a3eb09e70c534a70ea3f705620ce4bff75e4fd52f1e17ea7eb1ecf7095e2",
          "sha256": "2be1bc06700d34cdcc4ddcc6bfd6a8d1853db16b86b28db6c1db4feb39a25124",
          "sha1": "93417c6946f22464403976504a23735aa715d818",
          "md5": "3861136a7df5baf7439577f399319fb1"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-lib-common-metadata/0.17.0/kzen-lib-common-metadata-0.17.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-metadata",
        "version": "0.17.0"
      }
    }
  ]
}
