{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.27.0/kzen-auto-common-0.27.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.27.0.jar",
          "url": "kzen-auto-common-jvm-0.27.0.jar",
          "size": 583977,
          "sha512": "8e4901d4b85ec00027f3851e89fb2df28694b0bdc37bd64ed91b5d64951da808002c78a3230a468d4b20c2723ba4f95a73d1537850ef06f6e287af19e074fc70",
          "sha256": "2ea0d10e97e49754065c98d352086d459a0d8f87c1db59b869977125bebbc741",
          "sha1": "d9cbdb0fcb66d45e4053cbc401379878644b07d5",
          "md5": "cc98b2d5291e18bf1003b51a2edac2de"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.27.0.jar",
          "url": "kzen-auto-common-jvm-0.27.0.jar",
          "size": 583977,
          "sha512": "8e4901d4b85ec00027f3851e89fb2df28694b0bdc37bd64ed91b5d64951da808002c78a3230a468d4b20c2723ba4f95a73d1537850ef06f6e287af19e074fc70",
          "sha256": "2ea0d10e97e49754065c98d352086d459a0d8f87c1db59b869977125bebbc741",
          "sha1": "d9cbdb0fcb66d45e4053cbc401379878644b07d5",
          "md5": "cc98b2d5291e18bf1003b51a2edac2de"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.27.0-sources.jar",
          "url": "kzen-auto-common-jvm-0.27.0-sources.jar",
          "size": 146454,
          "sha512": "8b9b930e99ce8612db55ef8888e4e798779a5e9f0907bab74e44917250f0631b86af6edd737f30062f30fc97232b4c0b54dcb95a6f6bbdf202a4fd85714dedd3",
          "sha256": "4f6e1ce1ffa65e90da693c1b84405bd0c392537c30b4605403f8d5970c474323",
          "sha1": "b9b57ec5800379dea8ec82a350a1f665ff88d6dd",
          "md5": "4839399051daf84dd398ff5da6571eec"
        }
      ]
    }
  ]
}
