{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.25.0/kzen-auto-common-0.25.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.25.0.jar",
          "url": "kzen-auto-common-js-0.25.0.jar",
          "size": 308073,
          "sha512": "c84350f91fe9fc9a5d4a8ef5e591e8779fd5466aa39fcb64b5fb06efcdb2d605d48717773437d2cbf0970efd9741740a04e029d6d7906321a62639113e739052",
          "sha256": "ef9b6d21a3f8479d3c060249e9cc979bc91f4ffb03d8a576cc0cc2acc1ae48e0",
          "sha1": "d4381094892aa99efb3c0c86948fcd8b908eb26c",
          "md5": "1204cbeb4a94818368e7fa644a6caeb2"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.344"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.25.0.jar",
          "url": "kzen-auto-common-js-0.25.0.jar",
          "size": 308073,
          "sha512": "c84350f91fe9fc9a5d4a8ef5e591e8779fd5466aa39fcb64b5fb06efcdb2d605d48717773437d2cbf0970efd9741740a04e029d6d7906321a62639113e739052",
          "sha256": "ef9b6d21a3f8479d3c060249e9cc979bc91f4ffb03d8a576cc0cc2acc1ae48e0",
          "sha1": "d4381094892aa99efb3c0c86948fcd8b908eb26c",
          "md5": "1204cbeb4a94818368e7fa644a6caeb2"
        }
      ]
    }
  ]
}
