{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.28.0/kzen-auto-common-0.28.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.28.0.klib",
          "url": "kzen-auto-common-js-0.28.0.klib",
          "size": 566926,
          "sha512": "e7edae0d4bb95fa5fa2bf3100fbe72968ec624ea1eef173c49de1570d002d9f4b78dcf276af3f313ffdd6fcf85c253d12c387562cd2622a3ae9dbea9e0db4ff2",
          "sha256": "0fa13fd3918e6b746156a97c547e3fd2f59cc8d6d1c772514bedb7547db3f5fd",
          "sha1": "40cd19faf08cf298279bf0b1863c29d5f0f29a09",
          "md5": "70e3a80faf8cf4f473bc1268453326c1"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.28.0.klib",
          "url": "kzen-auto-common-js-0.28.0.klib",
          "size": 566926,
          "sha512": "e7edae0d4bb95fa5fa2bf3100fbe72968ec624ea1eef173c49de1570d002d9f4b78dcf276af3f313ffdd6fcf85c253d12c387562cd2622a3ae9dbea9e0db4ff2",
          "sha256": "0fa13fd3918e6b746156a97c547e3fd2f59cc8d6d1c772514bedb7547db3f5fd",
          "sha1": "40cd19faf08cf298279bf0b1863c29d5f0f29a09",
          "md5": "70e3a80faf8cf4f473bc1268453326c1"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kzen-auto-common-js-0.28.0-sources.jar",
          "url": "kzen-auto-common-js-0.28.0-sources.jar",
          "size": 123128,
          "sha512": "d7c84580d27e7ac31c711ea45c4626cbcd44465753fab7c1dc174b147de1eb42e0154e4d2b3088f1c1fb38c3b0c8dc6735a92950843470958893ab6b782166fe",
          "sha256": "930933243bbf657879b235789223c79a5a5dc8eed4a5eea3f5119c0979e506b0",
          "sha1": "492faeb46d58b2c1c1e61c1fd980fdc55c013f1c",
          "md5": "443ceccb4d2d80d057e7c1baffc324de"
        }
      ]
    }
  ]
}
