{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.22.0.jar",
          "url": "kzen-auto-js-0.22.0.jar",
          "size": 451936,
          "sha512": "5c691af10b7ea7fe062f9ebe6c5e2aa739f0ebeaaaa8c8879e68d8761eafe2ee4d69b7765c92ca468af2d5e5fc8a0074510dd5433d97244bc87d48335381a809",
          "sha256": "e8645e23ca628bf7bd51d0d3854d60035c9532577a382b6d6b78fbd9eeb39236",
          "sha1": "be9df8b6993c9e4c788c1a47eafb2b8f83070d64",
          "md5": "396e8feecb91e37a4a6819829c211eca"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-assembly",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react",
          "version": {
            "requires": "17.0.2-pre.154-kotlin-1.5.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "17.0.2-pre.154-kotlin-1.5.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-styled",
          "version": {
            "requires": "5.2.3-pre.154-kotlin-1.5.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.154-kotlin-1.5.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.154-kotlin-1.5.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.22.0.jar",
          "url": "kzen-auto-js-0.22.0.jar",
          "size": 451936,
          "sha512": "5c691af10b7ea7fe062f9ebe6c5e2aa739f0ebeaaaa8c8879e68d8761eafe2ee4d69b7765c92ca468af2d5e5fc8a0074510dd5433d97244bc87d48335381a809",
          "sha256": "e8645e23ca628bf7bd51d0d3854d60035c9532577a382b6d6b78fbd9eeb39236",
          "sha1": "be9df8b6993c9e4c788c1a47eafb2b8f83070d64",
          "md5": "396e8feecb91e37a4a6819829c211eca"
        }
      ]
    },
    {
      "name": "jsCommonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
