{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-jvm",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "jrfng4mujfgoxmjj5evsnvfjjq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-jvm-0.21.0.jar",
          "url": "kzen-auto-jvm-0.21.0.jar",
          "size": 3988789,
          "sha512": "cc86202e154f1cb68d7e5fad0a41991593711fa886e8906d1a086060305105c373897443f70b8095624948dd3e01d0f94268d8181fa4269a39a6b2f8c2306d71",
          "sha256": "a376a0d0b3a60da718b9686c407e7642bf3c2fbcbdcefb009949049e8d8e9a65",
          "sha1": "2b72b11e169af57cdf04e664be357ebca1d36238",
          "md5": "3186791123f06b7e80323db039dbd018"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.144-kotlin-1.4.21"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux"
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-jvm",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "3.141.59"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.20"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "io.lacuna",
          "module": "bifurcan",
          "version": {
            "requires": "0.2.0-alpha4"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.lmax",
          "module": "disruptor",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "com.sangupta",
          "module": "bloomfilter",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-jvm-0.21.0.jar",
          "url": "kzen-auto-jvm-0.21.0.jar",
          "size": 3988789,
          "sha512": "cc86202e154f1cb68d7e5fad0a41991593711fa886e8906d1a086060305105c373897443f70b8095624948dd3e01d0f94268d8181fa4269a39a6b2f8c2306d71",
          "sha256": "a376a0d0b3a60da718b9686c407e7642bf3c2fbcbdcefb009949049e8d8e9a65",
          "sha1": "2b72b11e169af57cdf04e664be357ebca1d36238",
          "md5": "3186791123f06b7e80323db039dbd018"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kzen-auto-jvm-0.21.0-all.jar",
          "url": "kzen-auto-jvm-0.21.0-all.jar",
          "size": 114647787,
          "sha512": "0d83d7968221b4a71f6458f224086689a4b9a116bef52d810884a2d3c9062881e3aa236450ed6d09630980caa5b88853b6ff5994f518b101d1e0241a30a6fee9",
          "sha256": "6e4f48a5b62ebcf6c518116b39d32c548a75d0cd8a27ce62ea3e25cec387906f",
          "sha1": "a31ca7211ba3c0f76b7cce82f8d0f70d9f0fe993",
          "md5": "3c238f0b58759c6861624d124f5f5b55"
        }
      ]
    }
  ]
}
