{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-metadata-0.23.0.jar",
          "url": "kzen-auto-common-0.23.0.jar",
          "size": 132488,
          "sha512": "6cb1a012bc462a759270b4887607d5e32f8a9c4ec7930f8fa3a0d7b3b4ca8bdfecc35a2c49344cf913cf24c9067ae27081669b1ce3e734c4e235992dcb57c604",
          "sha256": "52751f75629466eafbb17a8ece7a36151441bff2c8bffa70f3a17f9844ebf0dd",
          "sha1": "4ad5c27ee485fc54cf3adac1ae358c617246c60f",
          "md5": "45d6d0c973f041f083387dea8a52a0eb"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-common-js/0.23.0/kzen-auto-common-js-0.23.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-js",
        "version": "0.23.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-common-js/0.23.0/kzen-auto-common-js-0.23.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-js",
        "version": "0.23.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-auto-common-jvm/0.23.0/kzen-auto-common-jvm-0.23.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-jvm",
        "version": "0.23.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-auto-common-jvm/0.23.0/kzen-auto-common-jvm-0.23.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-jvm",
        "version": "0.23.0"
      }
    }
  ]
}
