{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.26.0.jar",
          "url": "kzen-lib-jvm-0.26.0.jar",
          "size": 71739,
          "sha512": "487073346a02062c3115a20683a3e34e246eb1a7f0af84058b5827260c9844b3fc9fad46abb353bd047a7d319341a92e9f9af1ff467cf97b4e6d07701b79ff8a",
          "sha256": "d8c81981034dc16f2d99045ed098e69ab6bb420cb149a16e74fe83e13d307cd5",
          "sha1": "af9d475a94eb60017183f7aff943c4015240f6d5",
          "md5": "2b4e6ecfa82bef83d3946cc4a5f23ad0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.26.0.jar",
          "url": "kzen-lib-jvm-0.26.0.jar",
          "size": 71739,
          "sha512": "487073346a02062c3115a20683a3e34e246eb1a7f0af84058b5827260c9844b3fc9fad46abb353bd047a7d319341a92e9f9af1ff467cf97b4e6d07701b79ff8a",
          "sha256": "d8c81981034dc16f2d99045ed098e69ab6bb420cb149a16e74fe83e13d307cd5",
          "sha1": "af9d475a94eb60017183f7aff943c4015240f6d5",
          "md5": "2b4e6ecfa82bef83d3946cc4a5f23ad0"
        }
      ]
    }
  ]
}
