{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.22.0/kzen-auto-common-0.22.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.22.0.jar",
          "url": "kzen-auto-common-jvm-0.22.0.jar",
          "size": 611572,
          "sha512": "f31f56211bc3fe02fb5a212268c2ea9688179ab93efbbe3e5e82fcd98c1c78b8c5c1a2f737ee37ce5bd7eac9ca3bf15a943f7bfba9bf9ce453e7e777c87c9ba6",
          "sha256": "14a233b6b81aae85b2907c181c8c45e80ba8648adbb9d3766460db3bf067dc6f",
          "sha1": "e814604364bd1e7bc3641f8158180d00caf9033a",
          "md5": "144dc48bb7e4c813c4276b47e54612fc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.154-kotlin-1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.154-kotlin-1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.22.0.jar",
          "url": "kzen-auto-common-jvm-0.22.0.jar",
          "size": 611572,
          "sha512": "f31f56211bc3fe02fb5a212268c2ea9688179ab93efbbe3e5e82fcd98c1c78b8c5c1a2f737ee37ce5bd7eac9ca3bf15a943f7bfba9bf9ce453e7e777c87c9ba6",
          "sha256": "14a233b6b81aae85b2907c181c8c45e80ba8648adbb9d3766460db3bf067dc6f",
          "sha1": "e814604364bd1e7bc3641f8158180d00caf9033a",
          "md5": "144dc48bb7e4c813c4276b47e54612fc"
        }
      ]
    }
  ]
}
