{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.22.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.22.1.jar",
          "url": "kzen-lib-js-0.22.1.jar",
          "size": 45208,
          "sha512": "945d8fdbf73f254f9ab273d6995ca08b4124e616d5a2d718a8f5310bee2aec27069314977f27904aa62612298c22034750e74ee1acb3c299ea439d36e615ed3a",
          "sha256": "98722b1a452f396d31292cb9561a443178d255c37f94cabb440389c1ec3b7d04",
          "sha1": "a9ea240256fb18086f77c3dc8cb0ae7546fc4030",
          "md5": "0d32fc4ae135268174b8bf9a0e3ee46c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.22.1.jar",
          "url": "kzen-lib-js-0.22.1.jar",
          "size": 45208,
          "sha512": "945d8fdbf73f254f9ab273d6995ca08b4124e616d5a2d718a8f5310bee2aec27069314977f27904aa62612298c22034750e74ee1acb3c299ea439d36e615ed3a",
          "sha256": "98722b1a452f396d31292cb9561a443178d255c37f94cabb440389c1ec3b7d04",
          "sha1": "a9ea240256fb18086f77c3dc8cb0ae7546fc4030",
          "md5": "0d32fc4ae135268174b8bf9a0e3ee46c"
        }
      ]
    },
    {
      "name": "jsCommonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
