{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.19.0/kzen-auto-common-0.19.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "olrzopx3uraoxoa4kczf5f6sr4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.19.0.jar",
          "url": "kzen-auto-common-jvm-0.19.0.jar",
          "size": 512241,
          "sha512": "944228d9b88a39f69cf39c9e55ba67942efa5a9011ec4777206287a71198a905cf2d80deeb2392bee4b2f3a02d5fa479a995dd0fb2be321ed7419f0ea88b15e0",
          "sha256": "93f192f00c82ea0f0af431c2725f0e3187db545e3f5fced9dd7887111d054359",
          "sha1": "7c3a106e06a885ef1a5c00eac73a780097ad3f4d",
          "md5": "4a9373fa087e0a67079c8be7a2bfde0b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.129-kotlin-1.4.20"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.129-kotlin-1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.19.0.jar",
          "url": "kzen-auto-common-jvm-0.19.0.jar",
          "size": 512241,
          "sha512": "944228d9b88a39f69cf39c9e55ba67942efa5a9011ec4777206287a71198a905cf2d80deeb2392bee4b2f3a02d5fa479a995dd0fb2be321ed7419f0ea88b15e0",
          "sha256": "93f192f00c82ea0f0af431c2725f0e3187db545e3f5fced9dd7887111d054359",
          "sha1": "7c3a106e06a885ef1a5c00eac73a780097ad3f4d",
          "md5": "4a9373fa087e0a67079c8be7a2bfde0b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.19.0/kzen-auto-common-metadata-0.19.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.19.0"
      }
    }
  ]
}
