{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.20.0/kzen-auto-common-0.20.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "aikqswpvw5b77hgjpxupmqmmpy"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.20.0.jar",
          "url": "kzen-auto-common-js-0.20.0.jar",
          "size": 214418,
          "sha512": "e17779acf1f9368109715513a72a6db61432f0ddb6501fadb64b8805ccf36e5dc4adb34cfde49466104f358681074537a4f4b21bb3d09466deca3c34b7d7e2e3",
          "sha256": "b70f3a366e5ede97ace7f347ef6ffde2153af1f9cb829022cb4c91d7362c4158",
          "sha1": "50cce9caa091390f201f19cc4fb726e8989a9a14",
          "md5": "1736e29cc39cd2333734da2cc641578a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.134-kotlin-1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.20.0.jar",
          "url": "kzen-auto-common-js-0.20.0.jar",
          "size": 214418,
          "sha512": "e17779acf1f9368109715513a72a6db61432f0ddb6501fadb64b8805ccf36e5dc4adb34cfde49466104f358681074537a4f4b21bb3d09466deca3c34b7d7e2e3",
          "sha256": "b70f3a366e5ede97ace7f347ef6ffde2153af1f9cb829022cb4c91d7362c4158",
          "sha1": "50cce9caa091390f201f19cc4fb726e8989a9a14",
          "md5": "1736e29cc39cd2333734da2cc641578a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.20.0/kzen-auto-common-metadata-0.20.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.20.0"
      }
    }
  ]
}
