{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "jrfng4mujfgoxmjj5evsnvfjjq"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.21.0.jar",
          "url": "kzen-auto-js-0.21.0.jar",
          "size": 428676,
          "sha512": "771ed6f0e6bf509569e06b0ce2455e43ef57c322af00d428b36c92566628e317cadfeb033396d604edc6b05e57dd5202e117afd1f980f60c421c1a8f4800e236",
          "sha256": "15e74f9d0f9faf8d239ea328e352d01ca81185ebd1b18dd0c53a43ceeb413403",
          "sha1": "b43b2e091e3987b01ef9dffa307e5413ae452da9",
          "md5": "808d331b45c2f19091b2dc4e7163ee46"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-assembly",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react",
          "version": {
            "requires": "17.0.1-pre.144-kotlin-1.4.21"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "17.0.1-pre.144-kotlin-1.4.21"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-styled",
          "version": {
            "requires": "5.2.0-pre.144-kotlin-1.4.21"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.144-kotlin-1.4.21"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.144-kotlin-1.4.21"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.21.0.jar",
          "url": "kzen-auto-js-0.21.0.jar",
          "size": 428676,
          "sha512": "771ed6f0e6bf509569e06b0ce2455e43ef57c322af00d428b36c92566628e317cadfeb033396d604edc6b05e57dd5202e117afd1f980f60c421c1a8f4800e236",
          "sha256": "15e74f9d0f9faf8d239ea328e352d01ca81185ebd1b18dd0c53a43ceeb413403",
          "sha1": "b43b2e091e3987b01ef9dffa307e5413ae452da9",
          "md5": "808d331b45c2f19091b2dc4e7163ee46"
        }
      ]
    },
    {
      "name": "jsCommonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
