{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.24.1.jar",
          "url": "kzen-lib-jvm-0.24.1.jar",
          "size": 60784,
          "sha512": "4072dc185a6634e244c30318652bb85088ca6e1ff91ca7aaf5c967bf30ac804673aeae33065268a4cc8a057fcf8a8999719c14330c0a4df463327e2819e1c347",
          "sha256": "e6a7169c9af2de7f634e3fa0c9b9fc1ca582c432daa14e699dbfa8da3d6e8649",
          "sha1": "e7ea286394c2add870548fd8ebb5ea4d8f6416ec",
          "md5": "f289eb352c1362738d735eafd54a3bef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.24.1.jar",
          "url": "kzen-lib-jvm-0.24.1.jar",
          "size": 60784,
          "sha512": "4072dc185a6634e244c30318652bb85088ca6e1ff91ca7aaf5c967bf30ac804673aeae33065268a4cc8a057fcf8a8999719c14330c0a4df463327e2819e1c347",
          "sha256": "e6a7169c9af2de7f634e3fa0c9b9fc1ca582c432daa14e699dbfa8da3d6e8649",
          "sha1": "e7ea286394c2add870548fd8ebb5ea4d8f6416ec",
          "md5": "f289eb352c1362738d735eafd54a3bef"
        }
      ]
    }
  ]
}
