{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-plugin",
    "version": "0.29.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "2026.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-plugin-0.29.1.jar",
          "url": "kzen-auto-plugin-0.29.1.jar",
          "size": 77077,
          "sha512": "8cd5b0d7e296074208665d25aeff585040985f3542e4dec00658fa5eb5f745149897ef0a32688bdb02a8729701b2af58eced02925fea7d049f840176b14bb084",
          "sha256": "58dbd62d239e35c42cd053380f38286193f0722d529526a8afdcaa6950488459",
          "sha1": "248f8a979977f534a7d150b3e7a25770ffc125b1",
          "md5": "9b04f6c596c10aed757c5230cf3f20ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "2026.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-plugin-0.29.1.jar",
          "url": "kzen-auto-plugin-0.29.1.jar",
          "size": 77077,
          "sha512": "8cd5b0d7e296074208665d25aeff585040985f3542e4dec00658fa5eb5f745149897ef0a32688bdb02a8729701b2af58eced02925fea7d049f840176b14bb084",
          "sha256": "58dbd62d239e35c42cd053380f38286193f0722d529526a8afdcaa6950488459",
          "sha1": "248f8a979977f534a7d150b3e7a25770ffc125b1",
          "md5": "9b04f6c596c10aed757c5230cf3f20ff"
        }
      ]
    }
  ]
}
