{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.24.0/kzen-auto-common-0.24.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.24.0.jar",
          "url": "kzen-auto-common-js-0.24.0.jar",
          "size": 304312,
          "sha512": "f01986fc6bc223b6dec7c4ac8a0933c10387421d0ee9c33ca2e7d442d6671c24040b0017d3347100ba3afa8962c851ef781e29a90f3dc31fb43a541ffdd6f5c6",
          "sha256": "cbe9bb4f1a8fa0c5cbc3404f1c0c4f6bfefc19a77638ebcb32ab026374d2e464",
          "sha1": "fddd27b21d5785c7c7dd907f49427a5f52fdea63",
          "md5": "92a10539b83f7d2d6e603e0bc8e84470"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.248-kotlin-1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.24.0.jar",
          "url": "kzen-auto-common-js-0.24.0.jar",
          "size": 304312,
          "sha512": "f01986fc6bc223b6dec7c4ac8a0933c10387421d0ee9c33ca2e7d442d6671c24040b0017d3347100ba3afa8962c851ef781e29a90f3dc31fb43a541ffdd6f5c6",
          "sha256": "cbe9bb4f1a8fa0c5cbc3404f1c0c4f6bfefc19a77638ebcb32ab026374d2e464",
          "sha1": "fddd27b21d5785c7c7dd907f49427a5f52fdea63",
          "md5": "92a10539b83f7d2d6e603e0bc8e84470"
        }
      ]
    }
  ]
}
