{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-metadata-0.27.0.jar",
          "url": "kzen-auto-common-0.27.0.jar",
          "size": 83872,
          "sha512": "8f3046fd8a067ca7d0c502159fa056cfb8a0bd4ba1b30736792c4fb803bc50d4a9a482fae87af18dfd5782d75f7ac513819d767fdca13187ba3925196150e348",
          "sha256": "f374023f0d84bd99024f3b7eb98e560da1347238707d2120732bd68200b3f0ee",
          "sha1": "fb43e50ea9fc7c5dc20353ffe3cf6794eca25513",
          "md5": "80fcb510f33a32b7fd874bf47c328508"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kzen-auto-common-kotlin-0.27.0-sources.jar",
          "url": "kzen-auto-common-0.27.0-sources.jar",
          "size": 143618,
          "sha512": "6e95283df77b022f88602d87ac1233e27612ddc651035812d7f7fe862ca2e52c2c2218007d34c3840b28a5a6a69d526ee9257b744eb3b2e78e380fb29d85799a",
          "sha256": "18be6c011c43192ef49790541d6db9f8e60257b7cc1f46f3b82cc7af68fdf0eb",
          "sha1": "d797814ccec3df7006827d070aca4f38f5344246",
          "md5": "acc2629ad907b50f5ce8aef45a0abb57"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-common-js/0.27.0/kzen-auto-common-js-0.27.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-js",
        "version": "0.27.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-common-js/0.27.0/kzen-auto-common-js-0.27.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-js",
        "version": "0.27.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-common-js/0.27.0/kzen-auto-common-js-0.27.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-js",
        "version": "0.27.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-auto-common-jvm/0.27.0/kzen-auto-common-jvm-0.27.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-jvm",
        "version": "0.27.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-auto-common-jvm/0.27.0/kzen-auto-common-jvm-0.27.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-jvm",
        "version": "0.27.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-auto-common-jvm/0.27.0/kzen-auto-common-jvm-0.27.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-jvm",
        "version": "0.27.0"
      }
    }
  ]
}
