{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.22.0/kzen-auto-common-0.22.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.22.0.jar",
          "url": "kzen-auto-common-js-0.22.0.jar",
          "size": 272732,
          "sha512": "dd7ebd17b4bf62df85bb1dd93a8dd4df6650be89315b0821869e20aadfe6775156809fa9625f0c3ea811cbcab64acd8957d1b19ad2a6851d746d22515a2921a2",
          "sha256": "b744bb4bf7baa7905336d7e0b04985462c3c08cf4970e3b39acfe2701cc508b2",
          "sha1": "d4c4ebe1b6901c660fad256af6b525cd94f183d1",
          "md5": "47fd2d5aa7b4c7f6c673bce6644265bd"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.154-kotlin-1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.22.0.jar",
          "url": "kzen-auto-common-js-0.22.0.jar",
          "size": 272732,
          "sha512": "dd7ebd17b4bf62df85bb1dd93a8dd4df6650be89315b0821869e20aadfe6775156809fa9625f0c3ea811cbcab64acd8957d1b19ad2a6851d746d22515a2921a2",
          "sha256": "b744bb4bf7baa7905336d7e0b04985462c3c08cf4970e3b39acfe2701cc508b2",
          "sha1": "d4c4ebe1b6901c660fad256af6b525cd94f183d1",
          "md5": "47fd2d5aa7b4c7f6c673bce6644265bd"
        }
      ]
    }
  ]
}
