{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "2iku5ntjuvbwtmfbdcudiiqn2y"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.21.0.jar",
          "url": "kzen-lib-js-0.21.0.jar",
          "size": 45113,
          "sha512": "31277ba071f1ece3c2f33cb59127aed3d61d9557e326ba33eda00372b4309ae91787480cb44f44c63bb805c92e027c216c60bf694af0e020a9a87613b30b1bd7",
          "sha256": "775cf2adfb7ec2422a33a68c12b41e751a7116b4fb31a581704cbf1f72d05c6d",
          "sha1": "789a4fc026f40cdd9e026dda2d8ee7b367b865ae",
          "md5": "4fa778ca264a9d8c7c4d9f56c128fe20"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.21.0.jar",
          "url": "kzen-lib-js-0.21.0.jar",
          "size": 45113,
          "sha512": "31277ba071f1ece3c2f33cb59127aed3d61d9557e326ba33eda00372b4309ae91787480cb44f44c63bb805c92e027c216c60bf694af0e020a9a87613b30b1bd7",
          "sha256": "775cf2adfb7ec2422a33a68c12b41e751a7116b4fb31a581704cbf1f72d05c6d",
          "sha1": "789a4fc026f40cdd9e026dda2d8ee7b367b865ae",
          "md5": "4fa778ca264a9d8c7c4d9f56c128fe20"
        }
      ]
    },
    {
      "name": "jsCommonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
