{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.27.0/kzen-auto-common-0.27.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.27.0.klib",
          "url": "kzen-auto-common-js-0.27.0.klib",
          "size": 523653,
          "sha512": "fea581197373bea86a9fadcbc8cae37f97ee79e803596889e373d6df11ce71d02b9f43b67d9abeb63e0cfdac18db5f926503e48ed5876eaad04650cf3ff758d1",
          "sha256": "e093809293f15ca3ec961f9b1fd5a7d3a8cd498715e95904358d399f0b025185",
          "sha1": "f8df0fe8faec4c0b49df81e22c9ea01bef86a6e4",
          "md5": "0afa816110eed802017adf00d46f0f70"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.27.0.klib",
          "url": "kzen-auto-common-js-0.27.0.klib",
          "size": 523653,
          "sha512": "fea581197373bea86a9fadcbc8cae37f97ee79e803596889e373d6df11ce71d02b9f43b67d9abeb63e0cfdac18db5f926503e48ed5876eaad04650cf3ff758d1",
          "sha256": "e093809293f15ca3ec961f9b1fd5a7d3a8cd498715e95904358d399f0b025185",
          "sha1": "f8df0fe8faec4c0b49df81e22c9ea01bef86a6e4",
          "md5": "0afa816110eed802017adf00d46f0f70"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kzen-auto-common-js-0.27.0-sources.jar",
          "url": "kzen-auto-common-js-0.27.0-sources.jar",
          "size": 145603,
          "sha512": "03223316977bcfa40e69194d20418d523cca940fe1381e8b11d5767d7f0bcd3063d0258e8fe13e76af937c50eb6bea29a6c5220dea657affff2dae682519c6c0",
          "sha256": "9a13979d2cdd080a9d33748afbcf4ab7e237759c7d62bbd5a0c885d50594d649",
          "sha1": "a96901d2995fa4bd5406b4a4aa41d2d3f289d232",
          "md5": "d87818a8aae0687d36b5bc39e6c77d38"
        }
      ]
    }
  ]
}
