{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-plugin",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-plugin-0.23.0.jar",
          "url": "kzen-auto-plugin-0.23.0.jar",
          "size": 51168,
          "sha512": "255021e165c0329bbf6ae88a1a19c7001eb997cfa3766dea31cba2b5c033a02c15e29104cad8e3b9b4b7d8be007e5b2a75c0d6a03fe1b11f7d45488a1a7dabec",
          "sha256": "0b13a24d6e7cb7ff35bca1e1635726306136930a156141d7976e0dadfd48c2e1",
          "sha1": "3acd1544389cb96d15a1140afbbb538317caab65",
          "md5": "b98b59db0604da573d18cedab294e5e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-plugin-0.23.0.jar",
          "url": "kzen-auto-plugin-0.23.0.jar",
          "size": 51168,
          "sha512": "255021e165c0329bbf6ae88a1a19c7001eb997cfa3766dea31cba2b5c033a02c15e29104cad8e3b9b4b7d8be007e5b2a75c0d6a03fe1b11f7d45488a1a7dabec",
          "sha256": "0b13a24d6e7cb7ff35bca1e1635726306136930a156141d7976e0dadfd48c2e1",
          "sha1": "3acd1544389cb96d15a1140afbbb538317caab65",
          "md5": "b98b59db0604da573d18cedab294e5e8"
        }
      ]
    }
  ]
}
