{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.17.0/kzen-lib-common-0.17.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "7r6gld2y75ah5l5nxf555zsv4u"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-metadata-0.17.0.jar",
          "url": "kzen-lib-common-metadata-0.17.0.jar",
          "size": 122748,
          "sha512": "dbabf3db4f2dc5e637d7ee99695ca03737f1937f1c044a26bc8b3072f1b52d581e1a8cfc21a03881db813fbdc371816af1258df1a827c390e739ea79f5ea26e2",
          "sha256": "3423260d1a3dc2ad87ba8b5437295a5bf4cd04055d3c9cb5baf6cde099bb63d9",
          "sha1": "759d77799ce98b1a06327e9b5b2ae47588ed3dd6",
          "md5": "e080b6c8ad99ea753b72662be9480e75"
        }
      ]
    }
  ]
}
