{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "18.2.0-pre.531"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "18.2.0-pre.531"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-emotion",
          "version": {
            "requires": "11.10.6-pre.531"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-mui",
          "version": {
            "requires": "5.9.1-pre.531"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.26.0.klib",
          "url": "kzen-auto-js-0.26.0.klib",
          "size": 1224326,
          "sha512": "374f6f70c8b42f2610e2f9f7112300648f04ba594e42fa1b9cae6747240293a8837b4d6bf64034d0bfea65961d4810b1e60de981df03a8cddfd4463ccd914b7c",
          "sha256": "7b61f453c6fcb2fd29159261af3e209f1675a0705b1672b790fe800aaef3b0d6",
          "sha1": "9986f55744039fdb8d1a8e1f3e9a8dcbb76f613b",
          "md5": "0cf4d24b5236c18c632eb6d2dda7886d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "18.2.0-pre.531"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "18.2.0-pre.531"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-emotion",
          "version": {
            "requires": "11.10.6-pre.531"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-mui",
          "version": {
            "requires": "5.9.1-pre.531"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.26.0.klib",
          "url": "kzen-auto-js-0.26.0.klib",
          "size": 1224326,
          "sha512": "374f6f70c8b42f2610e2f9f7112300648f04ba594e42fa1b9cae6747240293a8837b4d6bf64034d0bfea65961d4810b1e60de981df03a8cddfd4463ccd914b7c",
          "sha256": "7b61f453c6fcb2fd29159261af3e209f1675a0705b1672b790fe800aaef3b0d6",
          "sha1": "9986f55744039fdb8d1a8e1f3e9a8dcbb76f613b",
          "md5": "0cf4d24b5236c18c632eb6d2dda7886d"
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kzen-auto-js-0.26.0-sources.jar",
          "url": "kzen-auto-js-0.26.0-sources.jar",
          "size": 233534,
          "sha512": "4e8cb3a9fd4f8b6991250dd5c66bb5a7511bae14de400ff51c17135b92195b790e4900e0ccf9430e59e193472f199997fe54d3b3a06a6117fa33d009e1664c36",
          "sha256": "12c30a0c865c2508ff014e53bc43540791e096415d36bfad4f34b5184ab188b9",
          "sha1": "2f3a35a0c6ba7d5c336963c474a43037342f622b",
          "md5": "9c8e5a99afaa6c9d2ac5510cfd6c3a0d"
        }
      ]
    }
  ]
}
