{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-jvm",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-plugin",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-jvm",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux"
        },
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "3.141.59"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-jvm-0.24.0-plain.jar",
          "url": "kzen-auto-jvm-0.24.0-plain.jar",
          "size": 4470573,
          "sha512": "820503908307c59922e1dd869ccb30b6acbcfb66deda4e9031c250505de3fab29f89c1c5512a2e46f3917bea32dbb6acab47fed46a0c157906702adef282efaf",
          "sha256": "336c83511f7166a1b3e78149dfdfa38e89a72e5fa483af195ffaa3e8ab10e8ff",
          "sha1": "c954bd4796ddab800904d28d68c284454cef5d6b",
          "md5": "8d622cec890bcf4c356aa35332febada"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.248-kotlin-1.5.31"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil-core",
          "version": {
            "requires": "8.5.6"
          }
        },
        {
          "group": "io.lacuna",
          "module": "bifurcan",
          "version": {
            "requires": "0.2.0-alpha6"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.lmax",
          "module": "disruptor",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "com.sangupta",
          "module": "bloomfilter",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.linkedin.migz",
          "module": "migz",
          "version": {
            "requires": "2.0.beta-1"
          }
        },
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-plugin",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-jvm",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux"
        },
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "3.141.59"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-jvm-0.24.0-plain.jar",
          "url": "kzen-auto-jvm-0.24.0-plain.jar",
          "size": 4470573,
          "sha512": "820503908307c59922e1dd869ccb30b6acbcfb66deda4e9031c250505de3fab29f89c1c5512a2e46f3917bea32dbb6acab47fed46a0c157906702adef282efaf",
          "sha256": "336c83511f7166a1b3e78149dfdfa38e89a72e5fa483af195ffaa3e8ab10e8ff",
          "sha1": "c954bd4796ddab800904d28d68c284454cef5d6b",
          "md5": "8d622cec890bcf4c356aa35332febada"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kzen-auto-jvm-0.24.0-all.jar",
          "url": "kzen-auto-jvm-0.24.0-all.jar",
          "size": 102393212,
          "sha512": "79d5ec18d67762c0a82388413eaacfbe3dd575241c84f00e15c957c493c996234341a54b66dfad76d3400b2eac3de83036631a06136d31276e469ec1e526a5a9",
          "sha256": "6bb3b4ec3a4b6b5bdd2299b14be7378e0ed815d7e1d40ed2403914b7554cd646",
          "sha1": "c6be7c625d212441c911ba783fc47b1be5520ef7",
          "md5": "e7e4e54acfe586b4d0c9237b7dee3143"
        }
      ]
    }
  ]
}
