{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.28.0/kzen-lib-common-0.28.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.28.0.klib",
          "url": "kzen-lib-common-js-0.28.0.klib",
          "size": 693392,
          "sha512": "01a651928ac62e6af416c878e4b221e24926149d30599717083c9f5411e474346c2e9d64cf55b9b80ed9f53e9c8e07a0a4a22e7dc6909da39083f2d0c9eeec2d",
          "sha256": "e78675d8141e7d91e52938af54c05df07899cef77371226733235ae327ffe9c7",
          "sha1": "a9d28394603ff0367c4a63ee3571226eba595b0c",
          "md5": "48ffcdda24b75dfc3179e4b5c1243493"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.28.0.klib",
          "url": "kzen-lib-common-js-0.28.0.klib",
          "size": 693392,
          "sha512": "01a651928ac62e6af416c878e4b221e24926149d30599717083c9f5411e474346c2e9d64cf55b9b80ed9f53e9c8e07a0a4a22e7dc6909da39083f2d0c9eeec2d",
          "sha256": "e78675d8141e7d91e52938af54c05df07899cef77371226733235ae327ffe9c7",
          "sha1": "a9d28394603ff0367c4a63ee3571226eba595b0c",
          "md5": "48ffcdda24b75dfc3179e4b5c1243493"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kzen-lib-common-js-0.28.0-sources.jar",
          "url": "kzen-lib-common-js-0.28.0-sources.jar",
          "size": 126128,
          "sha512": "d6bcaf420f7d01d62375e61079e266b975cd0934893f3ce87f05d59cb048d7b9f8a7bcf28d1e9451267384785e187953f5c02bda41a87fcfcab21550695f0b60",
          "sha256": "8b429aad873b14bcfded0df658e5c052859f8a78bd8aabf104cb4c2f90790020",
          "sha1": "1a55ae976343bda42542c4023017b2cc3b88754f",
          "md5": "89f0d69691aa22cf36731bc580e300c6"
        }
      ]
    }
  ]
}
