{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.17.0/kzen-auto-common-0.17.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "qrhz64ljo5h2lkb6w7zxpomwny"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.17.0.jar",
          "url": "kzen-auto-common-jvm-0.17.0.jar",
          "size": 489727,
          "sha512": "345f8006807f07459e73f2e68039bd0c0d51878bc5d77eff3541c3dab7bacd80b06003b8fa5e22362f04e747082ddadae877d7a591db530221c840540783d98a",
          "sha256": "47c9df95150a3c244aff1c1d1aa6a4fe4a95ab7d63e7a4f9966782056d302a84",
          "sha1": "d95e6ec2e0ec429a74848e63fa29068308b4ed9e",
          "md5": "1149f6874d7fbeba07df357c53571b61"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.17.0.jar",
          "url": "kzen-auto-common-jvm-0.17.0.jar",
          "size": 489727,
          "sha512": "345f8006807f07459e73f2e68039bd0c0d51878bc5d77eff3541c3dab7bacd80b06003b8fa5e22362f04e747082ddadae877d7a591db530221c840540783d98a",
          "sha256": "47c9df95150a3c244aff1c1d1aa6a4fe4a95ab7d63e7a4f9966782056d302a84",
          "sha1": "d95e6ec2e0ec429a74848e63fa29068308b4ed9e",
          "md5": "1149f6874d7fbeba07df357c53571b61"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.17.0/kzen-auto-common-metadata-0.17.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.17.0"
      }
    }
  ]
}
