{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.24.1/kzen-lib-common-0.24.1.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.24.1.jar",
          "url": "kzen-lib-common-jvm-0.24.1.jar",
          "size": 622715,
          "sha512": "394117c189d20b5478aca938f5e4fe780367f9651f52db8a3fa537f2ecc44e4f4aa18a1c0e68e3ae76e8de16d5fa2d015fc1bb402e532198e43fd90e6e27ca0f",
          "sha256": "360d28f0dea1c968d8085b4ade20a7d7b97869dd970dd417268baa6f610c1a50",
          "sha1": "3a7c4352ab9b9d72eeca73f5f0152e813fd09661",
          "md5": "4f897c3277b7222aba5dbb01f1842ae7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.24.1.jar",
          "url": "kzen-lib-common-jvm-0.24.1.jar",
          "size": 622715,
          "sha512": "394117c189d20b5478aca938f5e4fe780367f9651f52db8a3fa537f2ecc44e4f4aa18a1c0e68e3ae76e8de16d5fa2d015fc1bb402e532198e43fd90e6e27ca0f",
          "sha256": "360d28f0dea1c968d8085b4ade20a7d7b97869dd970dd417268baa6f610c1a50",
          "sha1": "3a7c4352ab9b9d72eeca73f5f0152e813fd09661",
          "md5": "4f897c3277b7222aba5dbb01f1842ae7"
        }
      ]
    }
  ]
}
