{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.24.0.jar",
          "url": "kzen-lib-js-0.24.0.jar",
          "size": 45205,
          "sha512": "bdcb80943c6b36599d70ce3c40d22809501ac9bd172b1ad7566ab70a965b3f04ff5948af6f44b627c85ed4a079a21dd418338bd63808159acc8d7b911fdbeb96",
          "sha256": "2f5b9d15b5112b1f5cceb021a0e77c5ade2766b09ec42b290959d8321e005e68",
          "sha1": "7744c2cd79855db75caf28b927656b9bc155e152",
          "md5": "ab19f7cd952acd24eccaea59f18f13d9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.24.0.jar",
          "url": "kzen-lib-js-0.24.0.jar",
          "size": 45205,
          "sha512": "bdcb80943c6b36599d70ce3c40d22809501ac9bd172b1ad7566ab70a965b3f04ff5948af6f44b627c85ed4a079a21dd418338bd63808159acc8d7b911fdbeb96",
          "sha256": "2f5b9d15b5112b1f5cceb021a0e77c5ade2766b09ec42b290959d8321e005e68",
          "sha1": "7744c2cd79855db75caf28b927656b9bc155e152",
          "md5": "ab19f7cd952acd24eccaea59f18f13d9"
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
