{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "v35im6qiarc2bi7uzuwidtpecu"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.16.1.jar",
          "url": "kzen-auto-js-0.16.1.jar",
          "size": 360407,
          "sha512": "79dc7d20186ce4f399f55b5142c5f262250ad3307af3fd7d23b64508c2808d163c21e9f580687ccd057a86fb2f9e28c3f15bb5565db0c5536b8f5ec9a122ba8b",
          "sha256": "6ebc6f640afe3e7fd0145caf1e77d5e40b4918f45718f17e5e71b55312d713e5",
          "sha1": "999fda43a0d367ff83ae7b5589c64ea7be29ae9c",
          "md5": "3267b3115d47e6583b192d1544e48435"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.16.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-assembly",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react",
          "version": {
            "requires": "16.13.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "16.13.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-styled",
          "version": {
            "requires": "5.2.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.16.1.jar",
          "url": "kzen-auto-js-0.16.1.jar",
          "size": 360407,
          "sha512": "79dc7d20186ce4f399f55b5142c5f262250ad3307af3fd7d23b64508c2808d163c21e9f580687ccd057a86fb2f9e28c3f15bb5565db0c5536b8f5ec9a122ba8b",
          "sha256": "6ebc6f640afe3e7fd0145caf1e77d5e40b4918f45718f17e5e71b55312d713e5",
          "sha1": "999fda43a0d367ff83ae7b5589c64ea7be29ae9c",
          "md5": "3267b3115d47e6583b192d1544e48435"
        }
      ]
    },
    {
      "name": "js-jsCommonFakeApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
