{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.17.0/kzen-auto-common-0.17.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "qrhz64ljo5h2lkb6w7zxpomwny"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.17.0.jar",
          "url": "kzen-auto-common-js-0.17.0.jar",
          "size": 203601,
          "sha512": "33ad549b44d65e87c39344d48ceaecd78ca564ce6d23e6251e0e364c21b8ad604715b4f99851dfc9749c065493eef4536460ee4ff50ce595da20a94e01d7dd8f",
          "sha256": "d7934854b3b50955b2ccedfd8d750eafe1a92ff266106fa570c7656917e1a3ec",
          "sha1": "685fc4219c930fbaaf6bfeeb54e79b041f451251",
          "md5": "61b97b45b6ae196979def7f53cc5dd53"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.17.0.jar",
          "url": "kzen-auto-common-js-0.17.0.jar",
          "size": 203601,
          "sha512": "33ad549b44d65e87c39344d48ceaecd78ca564ce6d23e6251e0e364c21b8ad604715b4f99851dfc9749c065493eef4536460ee4ff50ce595da20a94e01d7dd8f",
          "sha256": "d7934854b3b50955b2ccedfd8d750eafe1a92ff266106fa570c7656917e1a3ec",
          "sha1": "685fc4219c930fbaaf6bfeeb54e79b041f451251",
          "md5": "61b97b45b6ae196979def7f53cc5dd53"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.17.0/kzen-auto-common-metadata-0.17.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.17.0"
      }
    }
  ]
}
