{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "qrhz64ljo5h2lkb6w7zxpomwny"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.17.0.jar",
          "url": "kzen-auto-js-0.17.0.jar",
          "size": 375878,
          "sha512": "756e216516949ae250ebf35002bfc28f77658a57dab51345be97564089fa5dde1ec5242667dd3d6c5abffdc3ffdc7dd749efe7bf216badec1d8c7e544ca24e5e",
          "sha256": "141f8df13fe3ff89978fb04d4317b83ded8a6245c3a8387799fae5fe20053898",
          "sha1": "3d3ff00ebef3048fdaabac7bc88ec25d35a49dd8",
          "md5": "6ab46e08be6aa08f4bbf3670529d0e6c"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-assembly",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react",
          "version": {
            "requires": "16.13.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "16.13.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-styled",
          "version": {
            "requires": "5.2.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.17.0.jar",
          "url": "kzen-auto-js-0.17.0.jar",
          "size": 375878,
          "sha512": "756e216516949ae250ebf35002bfc28f77658a57dab51345be97564089fa5dde1ec5242667dd3d6c5abffdc3ffdc7dd749efe7bf216badec1d8c7e544ca24e5e",
          "sha256": "141f8df13fe3ff89978fb04d4317b83ded8a6245c3a8387799fae5fe20053898",
          "sha1": "3d3ff00ebef3048fdaabac7bc88ec25d35a49dd8",
          "md5": "6ab46e08be6aa08f4bbf3670529d0e6c"
        }
      ]
    },
    {
      "name": "js-jsCommonFakeApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
