{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.26.0/kzen-auto-common-0.26.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.26.0.klib",
          "url": "kzen-auto-common-js-0.26.0.klib",
          "size": 620246,
          "sha512": "895cbda334c228cc55828a3e152003aac8f3e8824b3a585e781f69d8be0d27403132059cc7f97c2538d9d2b57d37734f594a47e261f7e42801bae3c7a7979659",
          "sha256": "7d5b122986e35ae1ff59850c84863e10fcff09fe8f10e15e3c5fd3f273a1c61e",
          "sha1": "5da69371b92ad8795f05f5963ccd687d0bb7db97",
          "md5": "af8f0e4195ec6099e4021cbd2b7e3233"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.26.0.klib",
          "url": "kzen-auto-common-js-0.26.0.klib",
          "size": 620246,
          "sha512": "895cbda334c228cc55828a3e152003aac8f3e8824b3a585e781f69d8be0d27403132059cc7f97c2538d9d2b57d37734f594a47e261f7e42801bae3c7a7979659",
          "sha256": "7d5b122986e35ae1ff59850c84863e10fcff09fe8f10e15e3c5fd3f273a1c61e",
          "sha1": "5da69371b92ad8795f05f5963ccd687d0bb7db97",
          "md5": "af8f0e4195ec6099e4021cbd2b7e3233"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kzen-auto-common-js-0.26.0-sources.jar",
          "url": "kzen-auto-common-js-0.26.0-sources.jar",
          "size": 145237,
          "sha512": "bae5ab2355341ea0d433ad2b11ab1c2adf306391affb508564f3f717a8edaaaca49ce40c58d32274bc968452a703d546b09627f17f37bf20c530c0d6a0de6cf8",
          "sha256": "e662830d73acd65ae53f6ede46842c6bfa4611327158fbadf52775943ec4f28e",
          "sha1": "344f7717069dfb9d6d6e2f86bff427b75d5a24d4",
          "md5": "950c7799c59e345c2e063b9c8a066d82"
        }
      ]
    }
  ]
}
