{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.28.0.jar",
          "url": "kzen-lib-jvm-0.28.0.jar",
          "size": 71553,
          "sha512": "cb5f320542caeaf270997e400ccccfb1a1c160cc4b308c6905c5544f2d0aa69a3a412de5ee01448802548aaa961704651eeb416018de7007c33d4fb6b277cf73",
          "sha256": "bb75c9c543cc7fab307534271930b2db699d738b1fe565f93e37de773fa6749a",
          "sha1": "85b05bffe29e25f1d61e889c0f462fd02d0dacbb",
          "md5": "bb6869bbb4a0dcefab5a5c2ca8627f81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.2.0-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.28.0.jar",
          "url": "kzen-lib-jvm-0.28.0.jar",
          "size": 71553,
          "sha512": "cb5f320542caeaf270997e400ccccfb1a1c160cc4b308c6905c5544f2d0aa69a3a412de5ee01448802548aaa961704651eeb416018de7007c33d4fb6b277cf73",
          "sha256": "bb75c9c543cc7fab307534271930b2db699d738b1fe565f93e37de773fa6749a",
          "sha1": "85b05bffe29e25f1d61e889c0f462fd02d0dacbb",
          "md5": "bb6869bbb4a0dcefab5a5c2ca8627f81"
        }
      ]
    }
  ]
}
