{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.18.0/kzen-auto-common-0.18.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "leyf5vl4inefveeqp6jncc6z3i"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.18.0.jar",
          "url": "kzen-auto-common-js-0.18.0.jar",
          "size": 210034,
          "sha512": "b85f7aaf7e701110ef86d95cd3ca6235aeca90e0c52b2ffbcdfec65164cdbdc0d82f3e735fa9e1d346e87477d478a1a2054ff6f825f061e664946b9847b0575f",
          "sha256": "9e9956143948e1d807818769d7850acc9247607320594d0bf627c9d67c4fd546",
          "sha1": "0a2b619cd91bfee3827faa3d3853f8f7eabfaff4",
          "md5": "d448e09bf868154529578332de7ec76e"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.18.0.jar",
          "url": "kzen-auto-common-js-0.18.0.jar",
          "size": 210034,
          "sha512": "b85f7aaf7e701110ef86d95cd3ca6235aeca90e0c52b2ffbcdfec65164cdbdc0d82f3e735fa9e1d346e87477d478a1a2054ff6f825f061e664946b9847b0575f",
          "sha256": "9e9956143948e1d807818769d7850acc9247607320594d0bf627c9d67c4fd546",
          "sha1": "0a2b619cd91bfee3827faa3d3853f8f7eabfaff4",
          "md5": "d448e09bf868154529578332de7ec76e"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.18.0/kzen-auto-common-metadata-0.18.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.18.0"
      }
    }
  ]
}
