{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.18.0/kzen-auto-common-0.18.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tlvpymcfkzbztmdd57r4yaqt44"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.18.0.jar",
          "url": "kzen-auto-common-js-0.18.0.jar",
          "size": 210034,
          "sha512": "f5bb8568387dde2528e4dcc191554879ffc29b6f3170301304523a400ac143b21e82fc69151bf2b8b59ba51f74b691332eceafbfc4713088cfc5ef8073302988",
          "sha256": "27188a39dc05abea0acfa87dd5196d7191c4bc32af12424ff9e71ea75c4f0725",
          "sha1": "37e0f67a050347a3e2e8c9ea1e94326445a39682",
          "md5": "cd1e1a5a13fd37ae70823587b6152f36"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.18.0.jar",
          "url": "kzen-auto-common-js-0.18.0.jar",
          "size": 210034,
          "sha512": "f5bb8568387dde2528e4dcc191554879ffc29b6f3170301304523a400ac143b21e82fc69151bf2b8b59ba51f74b691332eceafbfc4713088cfc5ef8073302988",
          "sha256": "27188a39dc05abea0acfa87dd5196d7191c4bc32af12424ff9e71ea75c4f0725",
          "sha1": "37e0f67a050347a3e2e8c9ea1e94326445a39682",
          "md5": "cd1e1a5a13fd37ae70823587b6152f36"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.18.0/kzen-auto-common-metadata-0.18.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.18.0"
      }
    }
  ]
}
