{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qy2plcrkgrg75pocbnl4xgwwbq"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.19.0.jar",
          "url": "kzen-lib-js-0.19.0.jar",
          "size": 45112,
          "sha512": "d759ecf2217d3de183f4bfef36141da3bf4464ef2162d04bf84df1743dbae2e95b90c904fd2592854ff9e323105d8be201151ea7d46d9d5a41eac20c118f1d9c",
          "sha256": "23af0fe9b4ce78bb4e0a634822e817612375c0eb3ec41d882f0741da3ac8cd30",
          "sha1": "59186bade2580c5d1eb9c412e588c9ec9d28a73e",
          "md5": "ab11a681131d93c3043f70b9a8f1e840"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.19.0.jar",
          "url": "kzen-lib-js-0.19.0.jar",
          "size": 45112,
          "sha512": "d759ecf2217d3de183f4bfef36141da3bf4464ef2162d04bf84df1743dbae2e95b90c904fd2592854ff9e323105d8be201151ea7d46d9d5a41eac20c118f1d9c",
          "sha256": "23af0fe9b4ce78bb4e0a634822e817612375c0eb3ec41d882f0741da3ac8cd30",
          "sha1": "59186bade2580c5d1eb9c412e588c9ec9d28a73e",
          "md5": "ab11a681131d93c3043f70b9a8f1e840"
        }
      ]
    },
    {
      "name": "jsCommonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
