{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-jvm",
    "version": "0.29.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-plugin",
          "version": {
            "requires": "0.29.1"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-jvm",
          "version": {
            "requires": "0.29.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.37"
          }
        },
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "4.45.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-jvm-0.29.1.jar",
          "url": "kzen-auto-jvm-0.29.1.jar",
          "size": 5364685,
          "sha512": "904cda10ff088c7cd91c3b53086da8a3bf58ca583e7b3183c260baf744e95ff57f848da0caa050af02f7e2976eb388ce15c5f070de1aa49617f8b256e9a2ddf9",
          "sha256": "66d38235706029e5dbc14c5c64ee27fe64f0090793e8323d65de27f00d5a3604",
          "sha1": "f6a03e1f9e7931362da146c44c502ea7853541cf",
          "md5": "bc80ba51e16d8532f2353a058fb9b867"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.29.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm-host",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-compiler-embeddable",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.github.bonigarcia",
          "module": "webdrivermanager",
          "version": {
            "requires": "6.3.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.28.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil-core",
          "version": {
            "requires": "8.5.18"
          }
        },
        {
          "group": "io.lacuna",
          "module": "bifurcan",
          "version": {
            "requires": "0.2.0-rc1"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.4.240"
          }
        },
        {
          "group": "com.lmax",
          "module": "disruptor",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.sangupta",
          "module": "bloomfilter",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.22.0"
          }
        },
        {
          "group": "com.linkedin.migz",
          "module": "migz",
          "version": {
            "requires": "2.0.beta-1"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-html-builder-jvm",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-jackson",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-plugin",
          "version": {
            "requires": "0.29.1"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-jvm",
          "version": {
            "requires": "0.29.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.37"
          }
        },
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "4.45.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-jvm-0.29.1.jar",
          "url": "kzen-auto-jvm-0.29.1.jar",
          "size": 5364685,
          "sha512": "904cda10ff088c7cd91c3b53086da8a3bf58ca583e7b3183c260baf744e95ff57f848da0caa050af02f7e2976eb388ce15c5f070de1aa49617f8b256e9a2ddf9",
          "sha256": "66d38235706029e5dbc14c5c64ee27fe64f0090793e8323d65de27f00d5a3604",
          "sha1": "f6a03e1f9e7931362da146c44c502ea7853541cf",
          "md5": "bc80ba51e16d8532f2353a058fb9b867"
        }
      ]
    }
  ]
}
