{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.17.1/kzen-lib-common-0.17.1.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "noqfyqhn7jae3nsy7bopcpo5uy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.17.1.jar",
          "url": "kzen-lib-common-jvm-0.17.1.jar",
          "size": 568650,
          "sha512": "e3435e19bb2b9651df831bcce26af9472ee94f0c7ea7597f1a1d1e678b9ecd2f5b474e0a71732329a566f64d9b656c5de3ec95f71bd4b7b48b2330743ea77cf2",
          "sha256": "242b68d6f4a0518d77523d99c790bd1b83423b34f823351bc9133cf48f1d4195",
          "sha1": "751468f6a22f38f33746e65ad9b8cd86f77008dc",
          "md5": "c92099ab9726b4415ae2b4db77936227"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.17.1.jar",
          "url": "kzen-lib-common-jvm-0.17.1.jar",
          "size": 568650,
          "sha512": "e3435e19bb2b9651df831bcce26af9472ee94f0c7ea7597f1a1d1e678b9ecd2f5b474e0a71732329a566f64d9b656c5de3ec95f71bd4b7b48b2330743ea77cf2",
          "sha256": "242b68d6f4a0518d77523d99c790bd1b83423b34f823351bc9133cf48f1d4195",
          "sha1": "751468f6a22f38f33746e65ad9b8cd86f77008dc",
          "md5": "c92099ab9726b4415ae2b4db77936227"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-lib-common-metadata/0.17.1/kzen-lib-common-metadata-0.17.1.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-metadata",
        "version": "0.17.1"
      }
    }
  ]
}
