{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6zhiom2d4fa3bjgh7gywfm5oji"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-metadata-0.20.0.jar",
          "url": "kzen-lib-common-0.20.0.jar",
          "size": 123209,
          "sha512": "e0a2a8531ca3d47945695a2be65ddee020fe28527d0dbc43b21a4d62927304031b6edcab8f1622b0069273065086df2ebe8b1d86877269495dfee0229d0d775f",
          "sha256": "9b39088e501cf1333517c830e678aa63e505dfeecfeb8a4302c53907db68bf5c",
          "sha1": "77e39af385b06d0b3ea69ae76c74d0ff25203d19",
          "md5": "56df202d5999cbfe9c36c917e3d8f209"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-lib-common-js/0.20.0/kzen-lib-common-js-0.20.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-js",
        "version": "0.20.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-lib-common-js/0.20.0/kzen-lib-common-js-0.20.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-js",
        "version": "0.20.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-lib-common-jvm/0.20.0/kzen-lib-common-jvm-0.20.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-jvm",
        "version": "0.20.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-lib-common-jvm/0.20.0/kzen-lib-common-jvm-0.20.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-jvm",
        "version": "0.20.0"
      }
    }
  ]
}
