{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.24.1/kzen-auto-common-0.24.1.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.24.1.jar",
          "url": "kzen-auto-common-jvm-0.24.1.jar",
          "size": 710757,
          "sha512": "5136e83433883968776a3746a144f1a12538def0acf68b652e8b6e1c65ca3be97c01578ea47a61a5fa8474620c2a35f6eaf0a1b341181201aed08c55036c8a83",
          "sha256": "d47e59c14c7fa67e616053d183ed6c71c044da12068bf9caf7900bf0efc49d06",
          "sha1": "a81e134e21a25802c905bd3203ba02e5da1b3ab8",
          "md5": "83eb8cd39e75f0cea14d8acdca775450"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.24.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.268-kotlin-1.6.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.268-kotlin-1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.24.1.jar",
          "url": "kzen-auto-common-jvm-0.24.1.jar",
          "size": 710757,
          "sha512": "5136e83433883968776a3746a144f1a12538def0acf68b652e8b6e1c65ca3be97c01578ea47a61a5fa8474620c2a35f6eaf0a1b341181201aed08c55036c8a83",
          "sha256": "d47e59c14c7fa67e616053d183ed6c71c044da12068bf9caf7900bf0efc49d06",
          "sha1": "a81e134e21a25802c905bd3203ba02e5da1b3ab8",
          "md5": "83eb8cd39e75f0cea14d8acdca775450"
        }
      ]
    }
  ]
}
