{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.24.0.jar",
          "url": "kzen-lib-jvm-0.24.0.jar",
          "size": 61082,
          "sha512": "439a0f734e7aa3edb6f897b09a678b5fc3e48061108e5a03893468bc2933089c7458a724d3d739c86aac1a91b3ec07d61adf5f3ec1b12b67ade6854408fff5b6",
          "sha256": "96b3c65034e5af14472159ca4568ad1765cb7319e4da467df1f15a0f8521af7a",
          "sha1": "cf1887f8c1c0ff68f1d411c3fbe70efb6bec2532",
          "md5": "d286fbdf9ee1ed6e075f5b10e0d76a29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.24.0.jar",
          "url": "kzen-lib-jvm-0.24.0.jar",
          "size": 61082,
          "sha512": "439a0f734e7aa3edb6f897b09a678b5fc3e48061108e5a03893468bc2933089c7458a724d3d739c86aac1a91b3ec07d61adf5f3ec1b12b67ade6854408fff5b6",
          "sha256": "96b3c65034e5af14472159ca4568ad1765cb7319e4da467df1f15a0f8521af7a",
          "sha1": "cf1887f8c1c0ff68f1d411c3fbe70efb6bec2532",
          "md5": "d286fbdf9ee1ed6e075f5b10e0d76a29"
        }
      ]
    }
  ]
}
