{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.23.0.jar",
          "url": "kzen-lib-js-0.23.0.jar",
          "size": 45205,
          "sha512": "2b45c273bcca9c3a14a252a73646c0253cb313ceb025a0df09ff8737891db072e6ec5657faf1baf607a22c65d75f2024b621c4e98a718a79a2b6461fd7e9aebe",
          "sha256": "f43bdf369e03fae8368ae8409ca50e832a087ad3798f0f85ad1f608229bf980f",
          "sha1": "2f416874ceef25fea4886b6525e0453dc5124d93",
          "md5": "294919bb44c820c7bfbb4c20c77c9f89"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.23.0.jar",
          "url": "kzen-lib-js-0.23.0.jar",
          "size": 45205,
          "sha512": "2b45c273bcca9c3a14a252a73646c0253cb313ceb025a0df09ff8737891db072e6ec5657faf1baf607a22c65d75f2024b621c4e98a718a79a2b6461fd7e9aebe",
          "sha256": "f43bdf369e03fae8368ae8409ca50e832a087ad3798f0f85ad1f608229bf980f",
          "sha1": "2f416874ceef25fea4886b6525e0453dc5124d93",
          "md5": "294919bb44c820c7bfbb4c20c77c9f89"
        }
      ]
    },
    {
      "name": "jsCommonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
