{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.16.0/kzen-auto-common-0.16.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "4htazsilf5gmvks7fvrjsvl6s4"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.16.0.jar",
          "url": "kzen-auto-common-js-0.16.0.jar",
          "size": 200666,
          "sha512": "6f346616400c08547c63165f96dfb05e9688e5f979a6313b8700d869e5d6faaa7d5827eb450b033f037321386e9618450ce331edad32a80d25dec829dc6fa159",
          "sha256": "002c69a626a0ebacdc466dac9e8bf7be2208e22ca9e880c227326905e37c4fc0",
          "sha1": "e9551090a1800ccc3791fec026351876b49dc2ab",
          "md5": "2bbfb5d982c16ab4c59a89873bec764d"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.16.0.jar",
          "url": "kzen-auto-common-js-0.16.0.jar",
          "size": 200666,
          "sha512": "6f346616400c08547c63165f96dfb05e9688e5f979a6313b8700d869e5d6faaa7d5827eb450b033f037321386e9618450ce331edad32a80d25dec829dc6fa159",
          "sha256": "002c69a626a0ebacdc466dac9e8bf7be2208e22ca9e880c227326905e37c4fc0",
          "sha1": "e9551090a1800ccc3791fec026351876b49dc2ab",
          "md5": "2bbfb5d982c16ab4c59a89873bec764d"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.16.0/kzen-auto-common-metadata-0.16.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.16.0"
      }
    }
  ]
}
