{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.18.1/kzen-auto-common-0.18.1.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "klvkzwkon5ab7pnlei5ta55gj4"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.18.1.jar",
          "url": "kzen-auto-common-js-0.18.1.jar",
          "size": 210246,
          "sha512": "2bc2788e118ae2a92ca3dddcdb8468924f6b9d1376e3107a08c452f9ef88c957171c553416df9160c0d55664a21d9dd4df3728ffc2a6f0a4bc24c479530d8947",
          "sha256": "5acd061f483219d7c95e159253a69dbe52b83318c180686b515fb331b7d35f27",
          "sha1": "342b319e7848479cccca28a503b8a21e6bb46ba5",
          "md5": "fa58d0483c8c74af6dfa869c8e85df95"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.18.1.jar",
          "url": "kzen-auto-common-js-0.18.1.jar",
          "size": 210246,
          "sha512": "2bc2788e118ae2a92ca3dddcdb8468924f6b9d1376e3107a08c452f9ef88c957171c553416df9160c0d55664a21d9dd4df3728ffc2a6f0a4bc24c479530d8947",
          "sha256": "5acd061f483219d7c95e159253a69dbe52b83318c180686b515fb331b7d35f27",
          "sha1": "342b319e7848479cccca28a503b8a21e6bb46ba5",
          "md5": "fa58d0483c8c74af6dfa869c8e85df95"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.18.1/kzen-auto-common-metadata-0.18.1.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.18.1"
      }
    }
  ]
}
