{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "noqfyqhn7jae3nsy7bopcpo5uy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.17.1.jar",
          "url": "kzen-lib-js-0.17.1.jar",
          "size": 45079,
          "sha512": "99888049aebe7eff276547141d0325e4fc51306ee1472316854b04124fe2cfd0e01586331d6512241039c422f63ab396618c07a23efc3e45830694a964cca42c",
          "sha256": "497ae21560b16d298640645e7b606644691caaf907a6fb1c1197a2f85b7b5fc5",
          "sha1": "63bfe0158e4708079f0316e85fb6a78d14e58f98",
          "md5": "1feb6eeea3127b22846ef13dbfa00d24"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.17.1.jar",
          "url": "kzen-lib-js-0.17.1.jar",
          "size": 45079,
          "sha512": "99888049aebe7eff276547141d0325e4fc51306ee1472316854b04124fe2cfd0e01586331d6512241039c422f63ab396618c07a23efc3e45830694a964cca42c",
          "sha256": "497ae21560b16d298640645e7b606644691caaf907a6fb1c1197a2f85b7b5fc5",
          "sha1": "63bfe0158e4708079f0316e85fb6a78d14e58f98",
          "md5": "1feb6eeea3127b22846ef13dbfa00d24"
        }
      ]
    },
    {
      "name": "js-jsCommonFakeApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
