{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.22.0/kzen-lib-common-0.22.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.22.0.jar",
          "url": "kzen-lib-common-jvm-0.22.0.jar",
          "size": 607275,
          "sha512": "228e6084125b3e710935864fc5b87dc6e0ce5d371d4d83bf7fac35e8945c1135c042c1e2a6727300cd309179600c7cfe753093ca61f9959361ca18cafe35c552",
          "sha256": "f2ba4a0bdcb8e4ab32dc6cbb3385af370f217eb6f7ed03ae94d0f007669ae53f",
          "sha1": "6ff8d967e7155a94304f6ba9da4ae77e229bfe12",
          "md5": "133e5005efeb3e4d751ceab37ee19410"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.22.0.jar",
          "url": "kzen-lib-common-jvm-0.22.0.jar",
          "size": 607275,
          "sha512": "228e6084125b3e710935864fc5b87dc6e0ce5d371d4d83bf7fac35e8945c1135c042c1e2a6727300cd309179600c7cfe753093ca61f9959361ca18cafe35c552",
          "sha256": "f2ba4a0bdcb8e4ab32dc6cbb3385af370f217eb6f7ed03ae94d0f007669ae53f",
          "sha1": "6ff8d967e7155a94304f6ba9da4ae77e229bfe12",
          "md5": "133e5005efeb3e4d751ceab37ee19410"
        }
      ]
    }
  ]
}
