{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.21.0/kzen-auto-common-0.21.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "jrfng4mujfgoxmjj5evsnvfjjq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.21.0.jar",
          "url": "kzen-auto-common-jvm-0.21.0.jar",
          "size": 557817,
          "sha512": "635ec8bda496667a302e0d3b247895bd07a8a62104e24aa433a8a4483be6923004bbed7237425aae640aad8b553c46f913212b4cd39f899adaaac75079daec56",
          "sha256": "86b59dd86f5e4f9094f342f42dae3d88a6e04a1a6dd60457d6e4b0ed4e0a066b",
          "sha1": "6540239e5172ad1015a194055c82b6e85ba99920",
          "md5": "0a7317d662dffb630f4413d29a52924e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.144-kotlin-1.4.21"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.144-kotlin-1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.21.0.jar",
          "url": "kzen-auto-common-jvm-0.21.0.jar",
          "size": 557817,
          "sha512": "635ec8bda496667a302e0d3b247895bd07a8a62104e24aa433a8a4483be6923004bbed7237425aae640aad8b553c46f913212b4cd39f899adaaac75079daec56",
          "sha256": "86b59dd86f5e4f9094f342f42dae3d88a6e04a1a6dd60457d6e4b0ed4e0a066b",
          "sha1": "6540239e5172ad1015a194055c82b6e85ba99920",
          "md5": "0a7317d662dffb630f4413d29a52924e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.21.0/kzen-auto-common-metadata-0.21.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.21.0"
      }
    }
  ]
}
