{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.23.0.jar",
          "url": "kzen-lib-jvm-0.23.0.jar",
          "size": 61244,
          "sha512": "5cc66df7243283ecd2e36806fbe5d5b6268f16d441eb2d205cd55c597457fb41231cc71259aa14ef8d68ed4dee9d354a07b91a5c0630b028c88c67291ac8c1c7",
          "sha256": "e4922186632687934e75c0805505dd069a52c85493090777ddce51ef462225e8",
          "sha1": "5e73d24cfa21cc7c03777aa73d0b9c739842560c",
          "md5": "2075fae954aebefe7792846b90f7f2de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.23.0.jar",
          "url": "kzen-lib-jvm-0.23.0.jar",
          "size": 61244,
          "sha512": "5cc66df7243283ecd2e36806fbe5d5b6268f16d441eb2d205cd55c597457fb41231cc71259aa14ef8d68ed4dee9d354a07b91a5c0630b028c88c67291ac8c1c7",
          "sha256": "e4922186632687934e75c0805505dd069a52c85493090777ddce51ef462225e8",
          "sha1": "5e73d24cfa21cc7c03777aa73d0b9c739842560c",
          "md5": "2075fae954aebefe7792846b90f7f2de"
        }
      ]
    }
  ]
}
