{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.17.1/kzen-lib-common-0.17.1.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "noqfyqhn7jae3nsy7bopcpo5uy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.17.1.jar",
          "url": "kzen-lib-common-js-0.17.1.jar",
          "size": 276568,
          "sha512": "a328b072aadac6ceb69ce14d10d2049a7cf9850881a508e40c58919952ec57efb733357daf964e21f406014af40c2ca04b290cfa0adde0eddb8820409a1e653a",
          "sha256": "433531f20ded4089de1ab9ea5ef059ee7d0781a6d7c43a43e5840e12f9bfd6b4",
          "sha1": "5a7c0e0aaf62c619fdd5b83ca46ce4df987046d4",
          "md5": "175876a3f8170b555125edc57fe3ea48"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.17.1.jar",
          "url": "kzen-lib-common-js-0.17.1.jar",
          "size": 276568,
          "sha512": "a328b072aadac6ceb69ce14d10d2049a7cf9850881a508e40c58919952ec57efb733357daf964e21f406014af40c2ca04b290cfa0adde0eddb8820409a1e653a",
          "sha256": "433531f20ded4089de1ab9ea5ef059ee7d0781a6d7c43a43e5840e12f9bfd6b4",
          "sha1": "5a7c0e0aaf62c619fdd5b83ca46ce4df987046d4",
          "md5": "175876a3f8170b555125edc57fe3ea48"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-lib-common-metadata/0.17.1/kzen-lib-common-metadata-0.17.1.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-metadata",
        "version": "0.17.1"
      }
    }
  ]
}
