{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "577r7knbyrelpmokwykjiznxpi"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.16.0.jar",
          "url": "kzen-lib-js-0.16.0.jar",
          "size": 45078,
          "sha512": "49d1ca2e20ad2e017aa2e189f148311b0bc100259284a92abfdc91ff3caf4658fa70b02d42da89efe810e7e39d794c0c8d12914114fd380bc7e065f87ef17b2f",
          "sha256": "4917ae2e40cb99a0d2a93e842703857e55c0acad34ecd756c3ceec1e6b8f9c3c",
          "sha1": "5ce2421d8a0157fb2dc6a4e5ec115e9da4ed72a6",
          "md5": "17b8a84687b44d4fed535f4727d1d0f4"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.16.0.jar",
          "url": "kzen-lib-js-0.16.0.jar",
          "size": 45078,
          "sha512": "49d1ca2e20ad2e017aa2e189f148311b0bc100259284a92abfdc91ff3caf4658fa70b02d42da89efe810e7e39d794c0c8d12914114fd380bc7e065f87ef17b2f",
          "sha256": "4917ae2e40cb99a0d2a93e842703857e55c0acad34ecd756c3ceec1e6b8f9c3c",
          "sha1": "5ce2421d8a0157fb2dc6a4e5ec115e9da4ed72a6",
          "md5": "17b8a84687b44d4fed535f4727d1d0f4"
        }
      ]
    },
    {
      "name": "js-jsCommonFakeApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
