{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.21.0/kzen-auto-common-0.21.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "jrfng4mujfgoxmjj5evsnvfjjq"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.21.0.jar",
          "url": "kzen-auto-common-js-0.21.0.jar",
          "size": 240522,
          "sha512": "c41f9730eb92cbcfdfd799b0447c0931aebd80ca6655709b0729949b704d3d5a9a1e450131fda6030102d2e9719e923a81ddf83cfd8c3277a9b46211263746ed",
          "sha256": "a41bd77bb4dd6f64c74fee57b720354ea76c329cc52918d50f32d1c2f4e2ce18",
          "sha1": "0b5eceafafaafddedff43ef84bb91e8ea3be5d71",
          "md5": "1b74ed4b0e43bcf6057b79082a57a834"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.144-kotlin-1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.21.0.jar",
          "url": "kzen-auto-common-js-0.21.0.jar",
          "size": 240522,
          "sha512": "c41f9730eb92cbcfdfd799b0447c0931aebd80ca6655709b0729949b704d3d5a9a1e450131fda6030102d2e9719e923a81ddf83cfd8c3277a9b46211263746ed",
          "sha256": "a41bd77bb4dd6f64c74fee57b720354ea76c329cc52918d50f32d1c2f4e2ce18",
          "sha1": "0b5eceafafaafddedff43ef84bb91e8ea3be5d71",
          "md5": "1b74ed4b0e43bcf6057b79082a57a834"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.21.0/kzen-auto-common-metadata-0.21.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.21.0"
      }
    }
  ]
}
