{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.16.0/kzen-lib-common-0.16.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "577r7knbyrelpmokwykjiznxpi"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.16.0.jar",
          "url": "kzen-lib-common-jvm-0.16.0.jar",
          "size": 561831,
          "sha512": "c4f74dde0ad63b53c7452d6912f3dfc06340ad3b56ea99beadec0a6553ccf4a7f792ea0324f97f85ebf4dfad936e40f8a53aa495d54ed925aa7ae3f2fbad8a16",
          "sha256": "dae788ecd17bf924ae0f0a428c1f0c983572c7f60a835e1b189a455b26a54263",
          "sha1": "f24f4cdbbce3fbd511a97d73071133ee2d0e7fc3",
          "md5": "206424a648c83a64eeb90627c1b245e8"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-jvm-0.16.0.jar",
          "url": "kzen-lib-common-jvm-0.16.0.jar",
          "size": 561831,
          "sha512": "c4f74dde0ad63b53c7452d6912f3dfc06340ad3b56ea99beadec0a6553ccf4a7f792ea0324f97f85ebf4dfad936e40f8a53aa495d54ed925aa7ae3f2fbad8a16",
          "sha256": "dae788ecd17bf924ae0f0a428c1f0c983572c7f60a835e1b189a455b26a54263",
          "sha1": "f24f4cdbbce3fbd511a97d73071133ee2d0e7fc3",
          "md5": "206424a648c83a64eeb90627c1b245e8"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-lib-common-metadata/0.16.0/kzen-lib-common-metadata-0.16.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-metadata",
        "version": "0.16.0"
      }
    }
  ]
}
