{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "2iku5ntjuvbwtmfbdcudiiqn2y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.21.0.jar",
          "url": "kzen-lib-jvm-0.21.0.jar",
          "size": 69517,
          "sha512": "90ebce20c54ca12e6ca7ad7577516bd95fb62c4081f19765a294ab20f68bdb2561cbea42525beae82a45254ddf07c43c52dcdf9d5c3f9043f26e5c389c925df0",
          "sha256": "96a05271444bef05caa9852c14558855e4ffc816c887903621f763ad50a32b4b",
          "sha1": "a9b447e13da81884ce912ea9a1a2b5b9cdbbfa78",
          "md5": "063a4f1a1dac790f9c195a1e4582e214"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.21.0.jar",
          "url": "kzen-lib-jvm-0.21.0.jar",
          "size": 69517,
          "sha512": "90ebce20c54ca12e6ca7ad7577516bd95fb62c4081f19765a294ab20f68bdb2561cbea42525beae82a45254ddf07c43c52dcdf9d5c3f9043f26e5c389c925df0",
          "sha256": "96a05271444bef05caa9852c14558855e4ffc816c887903621f763ad50a32b4b",
          "sha1": "a9b447e13da81884ce912ea9a1a2b5b9cdbbfa78",
          "md5": "063a4f1a1dac790f9c195a1e4582e214"
        }
      ]
    }
  ]
}
