{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-jvm",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tlvpymcfkzbztmdd57r4yaqt44"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-jvm-0.18.0.jar",
          "url": "kzen-auto-jvm-0.18.0.jar",
          "size": 3482224,
          "sha512": "ef842ab7f77912e6cdcf0e737671e854f40c73c0ac024c065a6c5c073987bf3b465622a1b26e4b9b85ad39c11b79a86bec7847134703eab6770b7459a0ee7436",
          "sha256": "5f253b9c24507a69afceb08757d385bd35e831121794288697b18c102d1bb659",
          "sha1": "3bcde97a7711163d1aea554bf029517fe8e2f496",
          "md5": "047d1c838c7b8dbc890909bca0806b82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux"
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-jvm",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "3.141.59"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.20"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "io.lacuna",
          "module": "bifurcan",
          "version": {
            "requires": "0.2.0-alpha4"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-jvm-0.18.0.jar",
          "url": "kzen-auto-jvm-0.18.0.jar",
          "size": 3482224,
          "sha512": "ef842ab7f77912e6cdcf0e737671e854f40c73c0ac024c065a6c5c073987bf3b465622a1b26e4b9b85ad39c11b79a86bec7847134703eab6770b7459a0ee7436",
          "sha256": "5f253b9c24507a69afceb08757d385bd35e831121794288697b18c102d1bb659",
          "sha1": "3bcde97a7711163d1aea554bf029517fe8e2f496",
          "md5": "047d1c838c7b8dbc890909bca0806b82"
        }
      ]
    }
  ]
}
