{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-js",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.25.0.jar",
          "url": "kzen-lib-js-0.25.0.jar",
          "size": 45545,
          "sha512": "36207702019a700a54a70a4b3db5a2ebb5172b0889c44b3652fd0a47d64bd1cb390eccd3fe747711e6ccec2c84bb219d616bc9ec5eb0459c1cd4ae84982998f2",
          "sha256": "8ead3384d7888c3dde0902fc6ac02b66dcead50bd9d3969ecb5e60cc1af8ed4c",
          "sha1": "f5eca3c7f3c0668862b3ec6d9b91bfaf9eaa1fb1",
          "md5": "3ef84a6e3f8b73ad2bba499eba051c0e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-js-0.25.0.jar",
          "url": "kzen-lib-js-0.25.0.jar",
          "size": 45545,
          "sha512": "36207702019a700a54a70a4b3db5a2ebb5172b0889c44b3652fd0a47d64bd1cb390eccd3fe747711e6ccec2c84bb219d616bc9ec5eb0459c1cd4ae84982998f2",
          "sha256": "8ead3384d7888c3dde0902fc6ac02b66dcead50bd9d3969ecb5e60cc1af8ed4c",
          "sha1": "f5eca3c7f3c0668862b3ec6d9b91bfaf9eaa1fb1",
          "md5": "3ef84a6e3f8b73ad2bba499eba051c0e"
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
