{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.24.1/kzen-lib-common-0.24.1.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.24.1.jar",
          "url": "kzen-lib-common-js-0.24.1.jar",
          "size": 297813,
          "sha512": "c3c3cee0fef05244de12b53e1f0488b3428e9d466efcf1183446e838a30d8ac47ffa5e6377627350a45526ccc34070c8fabcfaa2de80044da17431c50d137cac",
          "sha256": "0d37c917a599a5701589b0b0a6607a35a0c1a5b863c80b103ff90a136f0b0221",
          "sha1": "231166718f5746bb35b0eee26660b15c7700dd51",
          "md5": "9e28c31a9880069acb263a41708f7155"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.24.1.jar",
          "url": "kzen-lib-common-js-0.24.1.jar",
          "size": 297813,
          "sha512": "c3c3cee0fef05244de12b53e1f0488b3428e9d466efcf1183446e838a30d8ac47ffa5e6377627350a45526ccc34070c8fabcfaa2de80044da17431c50d137cac",
          "sha256": "0d37c917a599a5701589b0b0a6607a35a0c1a5b863c80b103ff90a136f0b0221",
          "sha1": "231166718f5746bb35b0eee26660b15c7700dd51",
          "md5": "9e28c31a9880069acb263a41708f7155"
        }
      ]
    }
  ]
}
