{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.16.1/kzen-auto-common-0.16.1.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "v35im6qiarc2bi7uzuwidtpecu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-metadata-0.16.1.jar",
          "url": "kzen-auto-common-metadata-0.16.1.jar",
          "size": 97461,
          "sha512": "420b6a8283f06872b75cffe631ebba2503b20d1537bb2ef3ddc615d32140610d1affa8f46744d93e25e8d8c681e02e698d4229e595d4b6005ca72016f6b73592",
          "sha256": "eeb9ba18d544691a3d7826068c07805736cebe87fd1ba9d20cf0799ab38fca76",
          "sha1": "476999a455f55b6dca9311323ef80d32465105bf",
          "md5": "b9598dab0a2d6c007bbcfbc4ab61c253"
        }
      ]
    }
  ]
}
