{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.28.1/kzen-auto-common-0.28.1.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.28.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.28.1.klib",
          "url": "kzen-auto-common-js-0.28.1.klib",
          "size": 567333,
          "sha512": "6a409b0faf00083659de226e42cbf1f67e771e260aee04167d258425db3b2df766557f154d087c4066168b6c8dc018fbd686c8b2c1b27b22469d5286dd104dea",
          "sha256": "ddd258211d11a0aaa0c875f3703a8fe41b3f7c9f074de9d8a51a9fdcc6cad46d",
          "sha1": "e3fbc925b055c483de7d86b02b1576c539e79100",
          "md5": "87c1fc8121919d28a0d8f2525b37ba6a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.28.1.klib",
          "url": "kzen-auto-common-js-0.28.1.klib",
          "size": 567333,
          "sha512": "6a409b0faf00083659de226e42cbf1f67e771e260aee04167d258425db3b2df766557f154d087c4066168b6c8dc018fbd686c8b2c1b27b22469d5286dd104dea",
          "sha256": "ddd258211d11a0aaa0c875f3703a8fe41b3f7c9f074de9d8a51a9fdcc6cad46d",
          "sha1": "e3fbc925b055c483de7d86b02b1576c539e79100",
          "md5": "87c1fc8121919d28a0d8f2525b37ba6a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kzen-auto-common-js-0.28.1-sources.jar",
          "url": "kzen-auto-common-js-0.28.1-sources.jar",
          "size": 123124,
          "sha512": "39e9516ea1e68914eb2f883da2045977dd2f8393f62c5759ecc030433746b0e59e6231581b89d3dfd1a5c68288870764ccc5cdccded6dfc3f0ec56c5ee159809",
          "sha256": "ef732ae9dd98c028104378adf53fa02741a9a84f17865e88f1b1401c1b77eabe",
          "sha1": "a09a55df189ae42bab8b80e2ee8d8e48c7a0033d",
          "md5": "595e2c7cbd27d6e8e4cb5c9e00288637"
        }
      ]
    }
  ]
}
