{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.24.0/kzen-auto-common-0.24.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.24.0.jar",
          "url": "kzen-auto-common-jvm-0.24.0.jar",
          "size": 712650,
          "sha512": "7591bb6356bfdca52373433abb20a380856fa76d75b1ea47542c0ed1bf60a6556cdd2e6f846fd2d442ebf7daf59e707fc9a03ab3179a6d623afaf91ce3bd3a32",
          "sha256": "7b829f7057a2f1788f6b8a243faaca600cb13ac934ec61e6ac49f1662fd67790",
          "sha1": "dc2b3ae56a3c4d2bfc5e8851acec4bf4edfa7f62",
          "md5": "22d7561136af2d161094f6885a026428"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.248-kotlin-1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.248-kotlin-1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.24.0.jar",
          "url": "kzen-auto-common-jvm-0.24.0.jar",
          "size": 712650,
          "sha512": "7591bb6356bfdca52373433abb20a380856fa76d75b1ea47542c0ed1bf60a6556cdd2e6f846fd2d442ebf7daf59e707fc9a03ab3179a6d623afaf91ce3bd3a32",
          "sha256": "7b829f7057a2f1788f6b8a243faaca600cb13ac934ec61e6ac49f1662fd67790",
          "sha1": "dc2b3ae56a3c4d2bfc5e8851acec4bf4edfa7f62",
          "md5": "22d7561136af2d161094f6885a026428"
        }
      ]
    }
  ]
}
