{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.22.0.jar",
          "url": "kzen-lib-jvm-0.22.0.jar",
          "size": 60837,
          "sha512": "7de803007abe5014dfb0f35e137e34b6cb24e97a7db16e15c95c9595004d14f04bab17800768e0302a5f8bfbf6f861a7c4a6f76405a2695715e9cf47bfb5deec",
          "sha256": "4cf4522e34ecb2909e3f4087549402a567f8e0de1d0ee664ddff0bb14abd6bd3",
          "sha1": "23b1063e25ae6811134cd73fbdef22b03b7c3625",
          "md5": "5bc3ffbf57d05302033bf1e950a1c378"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.22.0.jar",
          "url": "kzen-lib-jvm-0.22.0.jar",
          "size": 60837,
          "sha512": "7de803007abe5014dfb0f35e137e34b6cb24e97a7db16e15c95c9595004d14f04bab17800768e0302a5f8bfbf6f861a7c4a6f76405a2695715e9cf47bfb5deec",
          "sha256": "4cf4522e34ecb2909e3f4087549402a567f8e0de1d0ee664ddff0bb14abd6bd3",
          "sha1": "23b1063e25ae6811134cd73fbdef22b03b7c3625",
          "md5": "5bc3ffbf57d05302033bf1e950a1c378"
        }
      ]
    }
  ]
}
