{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.16.0/kzen-auto-common-0.16.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "4htazsilf5gmvks7fvrjsvl6s4"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.16.0.jar",
          "url": "kzen-auto-common-jvm-0.16.0.jar",
          "size": 475976,
          "sha512": "b32d243976766c70a74cfdd83cfba09368d5309e91b1f23de209b7063f3b1ffe0cd4eb7b261e20e0bfef0907a8daaddc78f800fff72be98a3e690cf7323cb1ef",
          "sha256": "2a1b683a66fe49bb6edd63e3c2e688d56165e2f3b608fd3bd071a6d3a99907e0",
          "sha1": "8846f1eceb3fe2f2a0cc277b5e0f79113b29bada",
          "md5": "2db5a06068e0db41dbddf9391edb2bd2"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.16.0.jar",
          "url": "kzen-auto-common-jvm-0.16.0.jar",
          "size": 475976,
          "sha512": "b32d243976766c70a74cfdd83cfba09368d5309e91b1f23de209b7063f3b1ffe0cd4eb7b261e20e0bfef0907a8daaddc78f800fff72be98a3e690cf7323cb1ef",
          "sha256": "2a1b683a66fe49bb6edd63e3c2e688d56165e2f3b608fd3bd071a6d3a99907e0",
          "sha1": "8846f1eceb3fe2f2a0cc277b5e0f79113b29bada",
          "md5": "2db5a06068e0db41dbddf9391edb2bd2"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.16.0/kzen-auto-common-metadata-0.16.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.16.0"
      }
    }
  ]
}
