{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.29.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.29.1.jar",
          "url": "kzen-lib-jvm-0.29.1.jar",
          "size": 96883,
          "sha512": "e158a3bbea93e46c41bf72bdd5fb9741c600441cf941b98fadbfe22e6da8cd77bb2cf0e66282a40ecc1e659ea197336d3ca85fa8ee42a57cea96fa41181433b0",
          "sha256": "83f06c32314cf900799b38fcfb5b26d4825b94e5c356640f241b7eae4116ae52",
          "sha1": "338dd18e80e61fae259798fc50601242c822c3f8",
          "md5": "f411404a863f39fabf259104e565c8f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.29.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.29.1.jar",
          "url": "kzen-lib-jvm-0.29.1.jar",
          "size": 96883,
          "sha512": "e158a3bbea93e46c41bf72bdd5fb9741c600441cf941b98fadbfe22e6da8cd77bb2cf0e66282a40ecc1e659ea197336d3ca85fa8ee42a57cea96fa41181433b0",
          "sha256": "83f06c32314cf900799b38fcfb5b26d4825b94e5c356640f241b7eae4116ae52",
          "sha1": "338dd18e80e61fae259798fc50601242c822c3f8",
          "md5": "f411404a863f39fabf259104e565c8f5"
        }
      ]
    }
  ]
}
