{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.24.0/kzen-lib-common-0.24.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.24.0.jar",
          "url": "kzen-lib-common-js-0.24.0.jar",
          "size": 300616,
          "sha512": "1e3a2cd284d726c04cf68e0a0d8fb7515d09f46ff31387c959bf2472f610d0f9854f4e6c56b20c5f3811ca6793a7c7a19fef85a84b45ea319a289db5e00ebe05",
          "sha256": "6aeff1399714d0f73a4ef922100e63bcb7c244b9d27d1b407c2f1ffb80f296fd",
          "sha1": "071e596f5e38601a3442377b9c75e4d1f3eb88ae",
          "md5": "5efee2882fe7acea39c8d4afbb730c26"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.24.0.jar",
          "url": "kzen-lib-common-js-0.24.0.jar",
          "size": 300616,
          "sha512": "1e3a2cd284d726c04cf68e0a0d8fb7515d09f46ff31387c959bf2472f610d0f9854f4e6c56b20c5f3811ca6793a7c7a19fef85a84b45ea319a289db5e00ebe05",
          "sha256": "6aeff1399714d0f73a4ef922100e63bcb7c244b9d27d1b407c2f1ffb80f296fd",
          "sha1": "071e596f5e38601a3442377b9c75e4d1f3eb88ae",
          "md5": "5efee2882fe7acea39c8d4afbb730c26"
        }
      ]
    }
  ]
}
