{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.17.1/kzen-lib-common-0.17.1.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "noqfyqhn7jae3nsy7bopcpo5uy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-metadata-0.17.1.jar",
          "url": "kzen-lib-common-metadata-0.17.1.jar",
          "size": 122748,
          "sha512": "e606873839d603d6622cc9b66d6b6c29d3a105d4cbfe4f0f51760588c7d3a76b3d0157fa835bc2992628744d68bbb749e22cab6253cce92fa0efba561b9ea8d2",
          "sha256": "124a20a33cfc85d1287cc4fc442148bc148a7e2b7c314f023ffe51e140d2636a",
          "sha1": "ed0a8277bf7fb16cf1b3dd22cb4182c3565bc8df",
          "md5": "555e867df1f115ff1692fc46c996775c"
        }
      ]
    }
  ]
}
