{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.25.0.jar",
          "url": "kzen-lib-jvm-0.25.0.jar",
          "size": 60414,
          "sha512": "e5b660818c6c8347ef26dec78da5db44fbfeba3ee5365482970ceb7af389f3805e5797dd0011dac0a7d48fe374c22add387ba913326c219984e4501a9e721392",
          "sha256": "bfb117a4c5d77cd061095489a827d90f47e936f051fc262c222e8ed0b4bc2913",
          "sha1": "5aa30f20a9c11ff7219a2d31e27d00302b330249",
          "md5": "84c1de1e72ad0e7fc39be6b38e6e8b79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.25.0.jar",
          "url": "kzen-lib-jvm-0.25.0.jar",
          "size": 60414,
          "sha512": "e5b660818c6c8347ef26dec78da5db44fbfeba3ee5365482970ceb7af389f3805e5797dd0011dac0a7d48fe374c22add387ba913326c219984e4501a9e721392",
          "sha256": "bfb117a4c5d77cd061095489a827d90f47e936f051fc262c222e8ed0b4bc2913",
          "sha1": "5aa30f20a9c11ff7219a2d31e27d00302b330249",
          "md5": "84c1de1e72ad0e7fc39be6b38e6e8b79"
        }
      ]
    }
  ]
}
