{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.22.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.22.1.jar",
          "url": "kzen-lib-jvm-0.22.1.jar",
          "size": 60837,
          "sha512": "e8393916361f0ac8211737270a56950cbf7c78c645a3e45760d15906ea036530d9a7c8727a1849b4b1ccbdb285a7041dae44cf897683c6619f74a6afd2ffc3fc",
          "sha256": "29f28d566f038ea570022b5d96a04acf8901a7d499851a85c8b94b49ebd650d2",
          "sha1": "700b5973ca432ab65bca9ad37bdcf22df4a4592d",
          "md5": "0e229bc993ea9cd980ad61079ea696b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.22.1.jar",
          "url": "kzen-lib-jvm-0.22.1.jar",
          "size": 60837,
          "sha512": "e8393916361f0ac8211737270a56950cbf7c78c645a3e45760d15906ea036530d9a7c8727a1849b4b1ccbdb285a7041dae44cf897683c6619f74a6afd2ffc3fc",
          "sha256": "29f28d566f038ea570022b5d96a04acf8901a7d499851a85c8b94b49ebd650d2",
          "sha1": "700b5973ca432ab65bca9ad37bdcf22df4a4592d",
          "md5": "0e229bc993ea9cd980ad61079ea696b7"
        }
      ]
    }
  ]
}
