{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.29.1/kzen-lib-common-0.29.1.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.29.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.29.1.klib",
          "url": "kzen-lib-common-js-0.29.1.klib",
          "size": 732593,
          "sha512": "874d03cdce9349c73740115d4ef296845f0c242e413e31c0c0005ec14511549627afd4971b8c955e548aa648c6f6fe7a2900a67cc8110e3beea015e49d623abd",
          "sha256": "7203f5dc235b2e37f0459fccecf4bb4ecc9928e6da4e323c0f61062e12d02ccc",
          "sha1": "0139e6666596f3074617da1c5a36a6dfe955967d",
          "md5": "39cc7e9c55127151a57fe17893ab9a86"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.29.1.klib",
          "url": "kzen-lib-common-js-0.29.1.klib",
          "size": 732593,
          "sha512": "874d03cdce9349c73740115d4ef296845f0c242e413e31c0c0005ec14511549627afd4971b8c955e548aa648c6f6fe7a2900a67cc8110e3beea015e49d623abd",
          "sha256": "7203f5dc235b2e37f0459fccecf4bb4ecc9928e6da4e323c0f61062e12d02ccc",
          "sha1": "0139e6666596f3074617da1c5a36a6dfe955967d",
          "md5": "39cc7e9c55127151a57fe17893ab9a86"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kzen-lib-common-js-0.29.1-sources.jar",
          "url": "kzen-lib-common-js-0.29.1-sources.jar",
          "size": 180285,
          "sha512": "4ecf544200a936fb7f0cbd4a6cd9e7fc1064ace821980183dc07ba96cf9611c0f2e2ec97d6b509646150b48d05ed07f0d53465494f3a74a028f8387d9813bf55",
          "sha256": "a48a6fd99cbdd30842761b8346b2e168cd887fa332fe7c0d596c151151ce45db",
          "sha1": "32cfd0f5c3c981666cd0b0caa3a972dc95e19142",
          "md5": "3dcd93503d7804ce80395981734983a2"
        }
      ]
    }
  ]
}
