{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "noqfyqhn7jae3nsy7bopcpo5uy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.17.1.jar",
          "url": "kzen-lib-jvm-0.17.1.jar",
          "size": 66280,
          "sha512": "386879146b9fe830cde722af0dffe4332bd995153e976d13de275f4a0ad542e62440468fa8ed9d43ba5f82c9782e75ff229a2e6a69ef94fe2549e21c7be36492",
          "sha256": "ec10474de5d78beb34872f58b6a420ab8433009c21ed9966c59171af1217aee2",
          "sha1": "7a1b0a6efa18178bfb74917b225e209aa99af181",
          "md5": "802b434a403e44536872024198153d57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.17.1.jar",
          "url": "kzen-lib-jvm-0.17.1.jar",
          "size": 66280,
          "sha512": "386879146b9fe830cde722af0dffe4332bd995153e976d13de275f4a0ad542e62440468fa8ed9d43ba5f82c9782e75ff229a2e6a69ef94fe2549e21c7be36492",
          "sha256": "ec10474de5d78beb34872f58b6a420ab8433009c21ed9966c59171af1217aee2",
          "sha1": "7a1b0a6efa18178bfb74917b225e209aa99af181",
          "md5": "802b434a403e44536872024198153d57"
        }
      ]
    }
  ]
}
