{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-plugin",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-plugin-0.26.0.jar",
          "url": "kzen-auto-plugin-0.26.0.jar",
          "size": 76646,
          "sha512": "d7e789e8011950a9869857ab0d10b546d37a889c6384a23d650c395fe12639272edc55303ceccd51507a8835ce6c3acc7c030a27fad161bf2665c42857f9eb7a",
          "sha256": "7ba312e8c1ff0695e34ce3c605e60a6e786ae68c9442cf181d00da762131e219",
          "sha1": "2ff9ad7740a957c812f7ddc94946d2920308c798",
          "md5": "7a23b2282584eeeeaf403877d00f0f2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-plugin-0.26.0.jar",
          "url": "kzen-auto-plugin-0.26.0.jar",
          "size": 76646,
          "sha512": "d7e789e8011950a9869857ab0d10b546d37a889c6384a23d650c395fe12639272edc55303ceccd51507a8835ce6c3acc7c030a27fad161bf2665c42857f9eb7a",
          "sha256": "7ba312e8c1ff0695e34ce3c605e60a6e786ae68c9442cf181d00da762131e219",
          "sha1": "2ff9ad7740a957c812f7ddc94946d2920308c798",
          "md5": "7a23b2282584eeeeaf403877d00f0f2f"
        }
      ]
    }
  ]
}
