{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-jvm",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "pkp2lucc5fbnxpas6hvmc6f264"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.18.0.jar",
          "url": "kzen-lib-jvm-0.18.0.jar",
          "size": 67575,
          "sha512": "4cd2e43549a9bd7c55dd4035e212d6836a8d1d6d55446f0066c7e6a11a0ad6778b4552dda30c5acd27037cbb8d26b8cc44fdf35ab652e9e6d195056e57e407dd",
          "sha256": "ff84a474f1315672ab0818ebd15dac841ea46dc4d2ea73141020cab8b30aeba2",
          "sha1": "cfa0965a35b0033b5453958ecd5fdd377f4719ed",
          "md5": "d48f1d2ef061ba54b72cdc4078f2e48a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.github.andrewoma.dexx",
          "module": "collection",
          "version": {
            "requires": "0.7"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-jvm-0.18.0.jar",
          "url": "kzen-lib-jvm-0.18.0.jar",
          "size": 67575,
          "sha512": "4cd2e43549a9bd7c55dd4035e212d6836a8d1d6d55446f0066c7e6a11a0ad6778b4552dda30c5acd27037cbb8d26b8cc44fdf35ab652e9e6d195056e57e407dd",
          "sha256": "ff84a474f1315672ab0818ebd15dac841ea46dc4d2ea73141020cab8b30aeba2",
          "sha1": "cfa0965a35b0033b5453958ecd5fdd377f4719ed",
          "md5": "d48f1d2ef061ba54b72cdc4078f2e48a"
        }
      ]
    }
  ]
}
