{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.22.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-metadata-0.22.1.jar",
          "url": "kzen-lib-common-0.22.1.jar",
          "size": 130909,
          "sha512": "0f274b717503f7c6166e343079c09fb5d56f581567e522f8b1b68ebe914a98b06b228b4bf3b67ff468bf8a3c653d6df14598d50fb5e3543b4641929f45427442",
          "sha256": "2eb8f3b2f70bdac08fbba2695064ad62aadba2cc1f19026332816f0f4f728d8c",
          "sha1": "6256e8a6632431ba83d7d205123d0e2d7b5483b6",
          "md5": "09402e67714350539dc60596ac9e733a"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-lib-common-js/0.22.1/kzen-lib-common-js-0.22.1.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-js",
        "version": "0.22.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-lib-common-js/0.22.1/kzen-lib-common-js-0.22.1.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-js",
        "version": "0.22.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-lib-common-jvm/0.22.1/kzen-lib-common-jvm-0.22.1.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-jvm",
        "version": "0.22.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-lib-common-jvm/0.22.1/kzen-lib-common-jvm-0.22.1.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-jvm",
        "version": "0.22.1"
      }
    }
  ]
}
