{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-metadata-0.27.0.jar",
          "url": "kzen-lib-common-0.27.0.jar",
          "size": 57210,
          "sha512": "5004c456d687fcc1cd6c00ecd354c60af95c6260554780522683b395b58f98d03e761bf415dddc77a50385dce6e821f0d91aea4127fe5c292c9704550778fa9b",
          "sha256": "cb2c71d27daa5e78130d73db33b22e13fd89268d7123288b3b8ae93af609604a",
          "sha1": "4d04426db1852e91397bfbfa7cd82efe1c075be8",
          "md5": "1a4e934842c446477083ea11120d68be"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kzen-lib-common-kotlin-0.27.0-sources.jar",
          "url": "kzen-lib-common-0.27.0-sources.jar",
          "size": 110587,
          "sha512": "768250f9d28dc6704029a56217d03c58d440f58c0168b12a82297a08f902e9bf2731223f69294e2d8cbf61fc016fe99e88feade8356f2b2c08d527c524417bb0",
          "sha256": "26f1be796a694936a1f6cc95df0a22a0633b0371fedf08ef87d06ecce7f25f74",
          "sha1": "99596cf265728bc4ac8fcb860a23fc2aa715f307",
          "md5": "dbc97c86bb89a88a67ba7db5f768ebfe"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-lib-common-js/0.27.0/kzen-lib-common-js-0.27.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-js",
        "version": "0.27.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-lib-common-js/0.27.0/kzen-lib-common-js-0.27.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-js",
        "version": "0.27.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-lib-common-js/0.27.0/kzen-lib-common-js-0.27.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-js",
        "version": "0.27.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-lib-common-jvm/0.27.0/kzen-lib-common-jvm-0.27.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-jvm",
        "version": "0.27.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-lib-common-jvm/0.27.0/kzen-lib-common-jvm-0.27.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-jvm",
        "version": "0.27.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-lib-common-jvm/0.27.0/kzen-lib-common-jvm-0.27.0.module",
        "group": "tech.kzen.lib",
        "module": "kzen-lib-common-jvm",
        "version": "0.27.0"
      }
    }
  ]
}
