{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.18.0/kzen-auto-common-0.18.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tlvpymcfkzbztmdd57r4yaqt44"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.18.0.jar",
          "url": "kzen-auto-common-jvm-0.18.0.jar",
          "size": 514630,
          "sha512": "f25b4f5006633983c4355600bbfcf64ea129cd34cf0d19391c1d9aa82c55a4f0e3f11a662f6e79b6e3b45d73a70c35b1e0b6ef24aa73fbd324a4db4ab035a783",
          "sha256": "d79821853d31cea79a511e994ec2c963c60ef07bb2d17d4d6fcfcf0f806eb3ed",
          "sha1": "772df6d26510d520b4dbe029f21bcc8c6205cc29",
          "md5": "ab57d287100fcaaeb4fc54d5b93189a1"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.18.0.jar",
          "url": "kzen-auto-common-jvm-0.18.0.jar",
          "size": 514630,
          "sha512": "f25b4f5006633983c4355600bbfcf64ea129cd34cf0d19391c1d9aa82c55a4f0e3f11a662f6e79b6e3b45d73a70c35b1e0b6ef24aa73fbd324a4db4ab035a783",
          "sha256": "d79821853d31cea79a511e994ec2c963c60ef07bb2d17d4d6fcfcf0f806eb3ed",
          "sha1": "772df6d26510d520b4dbe029f21bcc8c6205cc29",
          "md5": "ab57d287100fcaaeb4fc54d5b93189a1"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.18.0/kzen-auto-common-metadata-0.18.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.18.0"
      }
    }
  ]
}
