{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.18.0/kzen-auto-common-0.18.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "leyf5vl4inefveeqp6jncc6z3i"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.18.0.jar",
          "url": "kzen-auto-common-jvm-0.18.0.jar",
          "size": 514630,
          "sha512": "feb790639151d1fcc9cc41b85f121397de63070fcd72a84216ab3b2723dfdf827189338dfc8f7c0ba01b7f88449a309774a8f65cfacb39fdd498818246e6d92a",
          "sha256": "c629ba300e911862fbc0fa082d299c23f585db310c7f73a5e201bfa33aa0c649",
          "sha1": "b4b168e8ac606137f05c5a96fda3b2d98fbf0294",
          "md5": "8b06b77df9615913c8f03c253707e6c1"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-jvm",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-jvm",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-jvm-0.18.0.jar",
          "url": "kzen-auto-common-jvm-0.18.0.jar",
          "size": 514630,
          "sha512": "feb790639151d1fcc9cc41b85f121397de63070fcd72a84216ab3b2723dfdf827189338dfc8f7c0ba01b7f88449a309774a8f65cfacb39fdd498818246e6d92a",
          "sha256": "c629ba300e911862fbc0fa082d299c23f585db310c7f73a5e201bfa33aa0c649",
          "sha1": "b4b168e8ac606137f05c5a96fda3b2d98fbf0294",
          "md5": "8b06b77df9615913c8f03c253707e6c1"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kzen-auto-common-metadata/0.18.0/kzen-auto-common-metadata-0.18.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-metadata",
        "version": "0.18.0"
      }
    }
  ]
}
