{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-auto-common/0.23.0/kzen-auto-common-0.23.0.module",
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.23.0.jar",
          "url": "kzen-auto-common-js-0.23.0.jar",
          "size": 288821,
          "sha512": "0c865d820978a0c75cd4c2112261fb063f200a44272f5df41896c90dee29ee038dccef8fa0f1d4ed218e95fe0b708ec7855ca3978c31a2576b4ebe8621d48592",
          "sha256": "474a6fb9fd0ba3647dca15c66c8e70f18b9d297d6f9a64b7463cf45dc4b210ea",
          "sha1": "50813d69141dbb035c957dd08b4d31106c606c16",
          "md5": "18cc4014790021974bc704a2fd081b5c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css",
          "version": {
            "requires": "1.0.0-pre.213-kotlin-1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-js-0.23.0.jar",
          "url": "kzen-auto-common-js-0.23.0.jar",
          "size": 288821,
          "sha512": "0c865d820978a0c75cd4c2112261fb063f200a44272f5df41896c90dee29ee038dccef8fa0f1d4ed218e95fe0b708ec7855ca3978c31a2576b4ebe8621d48592",
          "sha256": "474a6fb9fd0ba3647dca15c66c8e70f18b9d297d6f9a64b7463cf45dc4b210ea",
          "sha1": "50813d69141dbb035c957dd08b4d31106c606c16",
          "md5": "18cc4014790021974bc704a2fd081b5c"
        }
      ]
    }
  ]
}
