{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.25.0/kzen-lib-common-0.25.0.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.25.0.jar",
          "url": "kzen-lib-common-js-0.25.0.jar",
          "size": 300113,
          "sha512": "268fd0a2ec28240bf5de36bbcfd3b8e35432fa25eab5bda2efad52c2852f0e3b36b8916e53977a8a6271d61a903e2738a753d182c41e24b781fafb00eafe2b21",
          "sha256": "9d870f2201f5678bc2bfe3aa7e261999bfc4103c28f3ad89a3dfbe19a969fc00",
          "sha1": "9d645d0522dc903a81e79ebe5951774aad36cfb8",
          "md5": "7783ac5a7fbfd69b7321b350d5bf2de0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.25.0.jar",
          "url": "kzen-lib-common-js-0.25.0.jar",
          "size": 300113,
          "sha512": "268fd0a2ec28240bf5de36bbcfd3b8e35432fa25eab5bda2efad52c2852f0e3b36b8916e53977a8a6271d61a903e2738a753d182c41e24b781fafb00eafe2b21",
          "sha256": "9d870f2201f5678bc2bfe3aa7e261999bfc4103c28f3ad89a3dfbe19a969fc00",
          "sha1": "9d645d0522dc903a81e79ebe5951774aad36cfb8",
          "md5": "7783ac5a7fbfd69b7321b350d5bf2de0"
        }
      ]
    }
  ]
}
