{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kzen-lib-common/0.22.1/kzen-lib-common-0.22.1.module",
    "group": "tech.kzen.lib",
    "module": "kzen-lib-common",
    "version": "0.22.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.22.1.jar",
          "url": "kzen-lib-common-js-0.22.1.jar",
          "size": 295920,
          "sha512": "4ff91f0f9a9193d20a8ed6961dba92135f846ce09a6f05e4f15aa2f4abfe8064b64f2a9303268c3fcee791879d263c74038d44b9814c037fcfea8f29e827e162",
          "sha256": "5fb8f887e9fae026ba585ef6b84abbe67cf2d05fee3f9fe4b91912293d38e4b6",
          "sha1": "04b0577720a01bb38fbadd773c3e3992e9aeab32",
          "md5": "f6489d89c2eb6353315e00cdc1ce952f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-lib-common-js-0.22.1.jar",
          "url": "kzen-lib-common-js-0.22.1.jar",
          "size": 295920,
          "sha512": "4ff91f0f9a9193d20a8ed6961dba92135f846ce09a6f05e4f15aa2f4abfe8064b64f2a9303268c3fcee791879d263c74038d44b9814c037fcfea8f29e827e162",
          "sha256": "5fb8f887e9fae026ba585ef6b84abbe67cf2d05fee3f9fe4b91912293d38e4b6",
          "sha1": "04b0577720a01bb38fbadd773c3e3992e9aeab32",
          "md5": "f6489d89c2eb6353315e00cdc1ce952f"
        }
      ]
    }
  ]
}
