{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-plugin",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-plugin-0.27.0.jar",
          "url": "kzen-auto-plugin-0.27.0.jar",
          "size": 76648,
          "sha512": "93dc46c27598f43971018f30f6247368952dce5d40c2edde1593d6573030c04ce6c0c081ce20b65d586ced787885ee08b4d0827316f34dc3e47313df6c02c125",
          "sha256": "1b9610e6f0861cc19c28576a02829919d34f7aa056e4493d888a37a12204b065",
          "sha1": "4a1ed6ba2e51bd3ea61258d0fc1c5d5af64c49d1",
          "md5": "4901db990932ee1aa1f778d1e4495b1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-plugin-0.27.0.jar",
          "url": "kzen-auto-plugin-0.27.0.jar",
          "size": 76648,
          "sha512": "93dc46c27598f43971018f30f6247368952dce5d40c2edde1593d6573030c04ce6c0c081ce20b65d586ced787885ee08b4d0827316f34dc3e47313df6c02c125",
          "sha256": "1b9610e6f0861cc19c28576a02829919d34f7aa056e4493d888a37a12204b065",
          "sha1": "4a1ed6ba2e51bd3ea61258d0fc1c5d5af64c49d1",
          "md5": "4901db990932ee1aa1f778d1e4495b1b"
        }
      ]
    }
  ]
}
