{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tlvpymcfkzbztmdd57r4yaqt44"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.18.0.jar",
          "url": "kzen-auto-js-0.18.0.jar",
          "size": 381187,
          "sha512": "c9bc0629daa96d7b2740320dadcbeb50d2eec5c52bb020c2fbdc407995275a4e2b9542099a1c3b7b0c3c3e872f173d253d050f860a953ad0fdf51ae922f59c1e",
          "sha256": "e26e9872d2303d7fd0da62a2099db5159902db928941f7462f5d19a64abe8724",
          "sha1": "7ebb03c37e4c1b58ded5ab4a74c06492540cc8f3",
          "md5": "f67b5eb1adfb8879152120855636f190"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-assembly",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react",
          "version": {
            "requires": "16.13.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "16.13.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-styled",
          "version": {
            "requires": "5.2.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.116-kotlin-1.4.10"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common-js",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.18.0.jar",
          "url": "kzen-auto-js-0.18.0.jar",
          "size": 381187,
          "sha512": "c9bc0629daa96d7b2740320dadcbeb50d2eec5c52bb020c2fbdc407995275a4e2b9542099a1c3b7b0c3c3e872f173d253d050f860a953ad0fdf51ae922f59c1e",
          "sha256": "e26e9872d2303d7fd0da62a2099db5159902db928941f7462f5d19a64abe8724",
          "sha1": "7ebb03c37e4c1b58ded5ab4a74c06492540cc8f3",
          "md5": "f67b5eb1adfb8879152120855636f190"
        }
      ]
    },
    {
      "name": "js-jsCommonFakeApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
