{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-js",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.24.0.jar",
          "url": "kzen-auto-js-0.24.0.jar",
          "size": 500041,
          "sha512": "a64c2994c799a64982f45f27e9f6375d8ec43962a971320e07fe894b1012e4ef30bab04ef5e5dfae5f857c9e147ff59d5998b083b8c7e13e4063826fe5738e28",
          "sha256": "290b1757e9c02707d4d1050bc3a61f9683de4624ed1f210d06ecef964a26dda4",
          "sha1": "4b62fe2113f0d4b3cfe8bf0a43d3e5e9261b8c02",
          "md5": "57ae401a9b0ca46fed628c1c052da886"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "tech.kzen.auto",
          "module": "kzen-auto-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-assembly",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "17.0.2-pre.248-kotlin-1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "17.0.2-pre.248-kotlin-1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-styled",
          "version": {
            "requires": "5.3.1-pre.248-kotlin-1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.248-kotlin-1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.248-kotlin-1.5.31"
          }
        },
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-js",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-js-0.24.0.jar",
          "url": "kzen-auto-js-0.24.0.jar",
          "size": 500041,
          "sha512": "a64c2994c799a64982f45f27e9f6375d8ec43962a971320e07fe894b1012e4ef30bab04ef5e5dfae5f857c9e147ff59d5998b083b8c7e13e4063826fe5738e28",
          "sha256": "290b1757e9c02707d4d1050bc3a61f9683de4624ed1f210d06ecef964a26dda4",
          "sha1": "4b62fe2113f0d4b3cfe8bf0a43d3e5e9261b8c02",
          "md5": "57ae401a9b0ca46fed628c1c052da886"
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    }
  ]
}
