{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.kzen.auto",
    "module": "kzen-auto-common",
    "version": "0.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.kzen.lib",
          "module": "kzen-lib-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kzen-auto-common-metadata-0.24.0.jar",
          "url": "kzen-auto-common-0.24.0.jar",
          "size": 139568,
          "sha512": "0048cbc5621d983d1287146d2c13f287490fd2ff21cdf28b0377449e9bef52a11c6419d66880655751506f42e268c270975c8ff60cbab0d7b675f1c023474358",
          "sha256": "eba3af890eb7f4076725711f89da8c02b2f341ca33e768d4c876b8e37572c8f8",
          "sha1": "6b17e23b943b07e70e11e383c5686b2aed92f09f",
          "md5": "fbf86451a03a0e18d95c039e7b120e61"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-common-js/0.24.0/kzen-auto-common-js-0.24.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-js",
        "version": "0.24.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kzen-auto-common-js/0.24.0/kzen-auto-common-js-0.24.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-js",
        "version": "0.24.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-auto-common-jvm/0.24.0/kzen-auto-common-jvm-0.24.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-jvm",
        "version": "0.24.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kzen-auto-common-jvm/0.24.0/kzen-auto-common-jvm-0.24.0.module",
        "group": "tech.kzen.auto",
        "module": "kzen-auto-common-jvm",
        "version": "0.24.0"
      }
    }
  ]
}
